/* คำศัพท์จากหนังสือ TOEIC "พิชิตคำศัพท์ TOEIC ใน 30 วัน" (ดึงจากรูปถ่าย IMG_2595–2895)
   ฟอร์แมต: {en, pos, th, ex, exTh, day}
   ===== ความคืบหน้า (อัปเดตทุกรอบ) =====
   เสร็จแล้ว: Day 01–08
   ทำต่อจาก: Day 09 — หน้า VOCABULARY อยู่ประมาณรูป IMG_2696 เป็นต้นไป
   (แต่ละ Day: หน้า VOCABULARY มา 3 สเปรด อยู่ถัดจากหน้า Daily Checkup)
   วิธีหาหน้า VOCABULARY: มองหาแถบสีเทา "คำศัพท์พื้นฐาน TOEIC" / "คำศัพท์พิชิต 800 คะแนน"
   (ข้ามหน้า WORD USE ที่มีคำหลักตัวใหญ่+ประโยคตัวอย่าง และข้ามหน้าแบบฝึกหัด Daily Checkup) */
const BOOK_WORDS = [
/* ===== DAY 01 : สมัครงาน / จ้างงาน ===== */
{en:"résumé",pos:"n.",th:"ประวัติย่อ (เรซูเม่)",ex:"Fax your résumé and cover letter to the above number.",exTh:"ส่งเรซูเม่และจดหมายแนะนำตัวไปที่เบอร์ข้างบน",day:1},
{en:"opening",pos:"n.",th:"ตำแหน่งงานว่าง, การเปิด",ex:"There are several job openings at the restaurant right now.",exTh:"ตอนนี้ร้านอาหารมีตำแหน่งงานว่างหลายตำแหน่ง",day:1},
{en:"applicant",pos:"n.",th:"ผู้สมัคร",ex:"Applicants are required to submit a résumé.",exTh:"ผู้สมัครต้องยื่นเรซูเม่",day:1},
{en:"requirement",pos:"n.",th:"ข้อกำหนด, สิ่งจำเป็น",ex:"A driver's license is a requirement of this job.",exTh:"ใบขับขี่เป็นสิ่งจำเป็นสำหรับงานนี้",day:1},
{en:"meet",pos:"v.",th:"มี/เป็นไปตาม, ตอบสนอง",ex:"Applicants must meet all the requirements for the job.",exTh:"ผู้สมัครต้องมีคุณสมบัติครบตามที่งานต้องการ",day:1},
{en:"qualified",pos:"adj.",th:"มีคุณสมบัติเหมาะสม",ex:"People with master's degrees are qualified for the research position.",exTh:"คนที่จบปริญญาโทมีคุณสมบัติเหมาะกับตำแหน่งวิจัย",day:1},
{en:"candidate",pos:"n.",th:"ผู้สมัคร, ผู้ท้าชิง",ex:"Five candidates will be selected for final interviews.",exTh:"ผู้สมัคร 5 คนจะถูกเลือกให้สัมภาษณ์รอบสุดท้าย",day:1},
{en:"confidence",pos:"n.",th:"ความมั่นใจ",ex:"We have confidence that she can handle the position.",exTh:"เรามั่นใจว่าเธอจะรับมือกับตำแหน่งนี้ได้",day:1},
{en:"highly",pos:"adv.",th:"อย่างมาก",ex:"Mr. Monroe's experience makes him highly qualified for the job.",exTh:"ประสบการณ์ของมิสเตอร์มอนโรทำให้เขาเหมาะกับงานนี้มาก",day:1},
{en:"professional",pos:"adj.",th:"มืออาชีพ, เชี่ยวชาญ",ex:"Jeff is known as a professional photographer.",exTh:"เจฟเป็นที่รู้จักในฐานะช่างภาพมืออาชีพ",day:1},
{en:"interview",pos:"n.",th:"การสัมภาษณ์",ex:"The interviews are being held in meeting room three.",exTh:"การสัมภาษณ์จัดขึ้นที่ห้องประชุมหมายเลข 3",day:1},
{en:"hire",pos:"v.",th:"จ้างงาน",ex:"The company expects to hire several new employees next month.",exTh:"บริษัทคาดว่าจะจ้างพนักงานใหม่หลายคนเดือนหน้า",day:1},
{en:"training",pos:"n.",th:"การฝึกอบรม",ex:"This company offers on-the-job training for new staff.",exTh:"บริษัทนี้มีการฝึกอบรมงานจริงให้พนักงานใหม่",day:1},
{en:"reference",pos:"n.",th:"การอ้างอิง, หนังสือรับรอง",ex:"Phillip asked his previous employer to write a reference letter for him.",exTh:"ฟิลลิปขอให้นายจ้างเก่าเขียนจดหมายรับรองให้",day:1},
{en:"position",pos:"n.",th:"ตำแหน่งงาน",ex:"The advertised position provides health care and other benefits.",exTh:"ตำแหน่งที่ประกาศให้สวัสดิการสุขภาพและผลประโยชน์อื่นๆ",day:1},
{en:"achievement",pos:"n.",th:"ความสำเร็จ, ผลงาน",ex:"List all of your achievements from previous jobs on your résumé.",exTh:"ระบุความสำเร็จจากงานก่อนหน้าทั้งหมดลงในเรซูเม่",day:1},
/* Day 01 VOCABULARY (พื้นฐาน + พิชิต 800) */
{en:"minimum",pos:"n.",th:"ขั้นต่ำ, น้อยที่สุด",ex:"",exTh:"",day:1},
{en:"party",pos:"n.",th:"งานเลี้ยง, ฝ่าย/คู่กรณี",ex:"",exTh:"",day:1},
{en:"plentiful",pos:"adj.",th:"มากมาย, อุดมสมบูรณ์",ex:"",exTh:"",day:1},
{en:"profession",pos:"n.",th:"อาชีพ, วิชาชีพ",ex:"",exTh:"",day:1},
{en:"achieve one's goal",pos:"phr.",th:"บรรลุเป้าหมาย",ex:"",exTh:"",day:1},
{en:"apprentice",pos:"n.",th:"ผู้ฝึกงาน, เด็กฝึกงาน",ex:"",exTh:"",day:1},
{en:"dress formally",pos:"phr.",th:"แต่งกายเป็นทางการ",ex:"",exTh:"",day:1},
{en:"dressed in suit",pos:"phr.",th:"แต่งกายในชุดสูท",ex:"",exTh:"",day:1},
{en:"figure out",pos:"phr.",th:"คิดหาคำตอบ, คำนวณออกมา",ex:"",exTh:"",day:1},
{en:"full-time work",pos:"phr.",th:"งานเต็มเวลา",ex:"",exTh:"",day:1},
{en:"job opportunity",pos:"phr.",th:"โอกาสในการทำงาน, ตำแหน่งงานที่เปิดรับ",ex:"",exTh:"",day:1},
{en:"job search",pos:"phr.",th:"การค้นหางาน, การหาตำแหน่งงานสมัคร",ex:"",exTh:"",day:1},
{en:"job seeker",pos:"phr.",th:"คนหางาน",ex:"",exTh:"",day:1},
{en:"lay out",pos:"phr.",th:"จัดวาง, จัดเรียงให้เห็น",ex:"",exTh:"",day:1},
{en:"letter of recommendation",pos:"phr.",th:"จดหมายรับรอง/แนะนำ",ex:"",exTh:"",day:1},
{en:"pay raise",pos:"phr.",th:"การเพิ่มเงินเดือน",ex:"",exTh:"",day:1},
{en:"practical experience",pos:"phr.",th:"ประสบการณ์เชิงปฏิบัติ",ex:"",exTh:"",day:1},
{en:"proof of employment",pos:"phr.",th:"หลักฐานการจ้างงาน",ex:"",exTh:"",day:1},
{en:"reapply",pos:"v.",th:"สมัครใหม่อีกครั้ง",ex:"",exTh:"",day:1},
{en:"recommendation letter",pos:"phr.",th:"จดหมายรับรองการทำงาน",ex:"",exTh:"",day:1},
{en:"reference letter",pos:"phr.",th:"จดหมายอ้างอิง/รับรอง",ex:"",exTh:"",day:1},
{en:"send off to",pos:"phr.",th:"ส่งไปยัง...",ex:"",exTh:"",day:1},
{en:"set up an interview",pos:"phr.",th:"นัดสัมภาษณ์งาน",ex:"",exTh:"",day:1},
{en:"take an examination",pos:"phr.",th:"เข้าสอบ, ทำการทดสอบ",ex:"",exTh:"",day:1},
{en:"training center",pos:"phr.",th:"ศูนย์ฝึกอบรม",ex:"",exTh:"",day:1},
{en:"waiting room",pos:"phr.",th:"ห้องรอสัมภาษณ์/ห้องรับรอง",ex:"",exTh:"",day:1},
{en:"well-educated",pos:"adj.",th:"มีการศึกษาดี",ex:"",exTh:"",day:1},
{en:"workstation",pos:"n.",th:"สถานีงาน, โต๊ะทำงาน",ex:"",exTh:"",day:1},
{en:"zealous",pos:"adj.",th:"กระตือรือร้น, กระหาย",ex:"",exTh:"",day:1},
{en:"cover letter",pos:"phr.",th:"จดหมายแนะนำตัว/ปะหน้า",ex:"",exTh:"",day:1},
{en:"devoted",pos:"adj.",th:"ทุ่มเท, อุทิศตัว",ex:"",exTh:"",day:1},
{en:"energetic",pos:"adj.",th:"มีกำลังวังชา, กระฉับกระเฉง",ex:"",exTh:"",day:1},
{en:"enthusiastic",pos:"adj.",th:"กระตือรือร้น",ex:"",exTh:"",day:1},
{en:"excel",pos:"v.",th:"เก่ง, เชี่ยวชาญ, ทำได้ดีเยี่ยม",ex:"",exTh:"",day:1},
{en:"exclude",pos:"v.",th:"ไม่รวม, กันออก",ex:"",exTh:"",day:1},
{en:"fluently",pos:"adv.",th:"อย่างคล่องแคล่ว",ex:"",exTh:"",day:1},
{en:"get through",pos:"phr.",th:"(สอบ) ผ่าน, ผ่านพ้นไปได้",ex:"",exTh:"",day:1},
{en:"match",pos:"v.",th:"เหมาะสม, เข้ากัน",ex:"",exTh:"",day:1},
{en:"necessity",pos:"n.",th:"ความจำเป็น, สิ่งจำเป็น",ex:"",exTh:"",day:1},
{en:"qualification",pos:"n.",th:"คุณสมบัติ",ex:"",exTh:"",day:1},
{en:"relevant",pos:"adj.",th:"ที่เกี่ยวข้อง",ex:"",exTh:"",day:1},
{en:"sign up for",pos:"phr.",th:"สมัคร, ลงทะเบียน",ex:"",exTh:"",day:1},
{en:"talented",pos:"adj.",th:"มีพรสวรรค์, มีความสามารถ",ex:"",exTh:"",day:1},
{en:"visiting",pos:"n.",th:"การเยี่ยมเยือน",ex:"",exTh:"",day:1},
{en:"workforce",pos:"n.",th:"แรงงาน, กำลังคนทำงาน",ex:"",exTh:"",day:1},
{en:"address the audience",pos:"phr.",th:"ปราศรัยต่อผู้ฟัง",ex:"",exTh:"",day:1},
{en:"be influenced by appearance",pos:"phr.",th:"ถูกชักจูงด้วยรูปลักษณ์ภายนอก",ex:"",exTh:"",day:1},
{en:"bilingual",pos:"adj.",th:"ที่ใช้สองภาษา",ex:"",exTh:"",day:1},
{en:"curriculum vitae (CV)",pos:"phr.",th:"ประวัติย่อ/ประวัติการศึกษาและการทำงาน",ex:"",exTh:"",day:1},
{en:"diploma",pos:"n.",th:"ประกาศนียบัตร, อนุปริญญา",ex:"",exTh:"",day:1},
{en:"endurance",pos:"n.",th:"ความอดทน",ex:"",exTh:"",day:1},
{en:"fluency",pos:"n.",th:"ความคล่องแคล่ว",ex:"",exTh:"",day:1},
{en:"fluent in",pos:"phr.",th:"คล่องแคล่วในเรื่อง...",ex:"",exTh:"",day:1},
{en:"go with",pos:"phr.",th:"เข้ากันได้กับ..., ไปด้วยกันกับ...",ex:"",exTh:"",day:1},
{en:"human resources",pos:"phr.",th:"ทรัพยากรบุคคล",ex:"",exTh:"",day:1},
{en:"improperly",pos:"adv.",th:"อย่างไม่เหมาะสม",ex:"",exTh:"",day:1},
{en:"in a positive manner",pos:"phr.",th:"ในทางที่ดี, ในเชิงบวก",ex:"",exTh:"",day:1},
{en:"in the field of",pos:"phr.",th:"ในสาขา...",ex:"",exTh:"",day:1},
{en:"inexperience",pos:"n.",th:"การขาดประสบการณ์",ex:"",exTh:"",day:1},
{en:"lack confidence",pos:"phr.",th:"ขาดความมั่นใจ",ex:"",exTh:"",day:1},
{en:"make A a regular habit",pos:"phr.",th:"ทำ A ให้เป็นนิสัย/กิจวัตร",ex:"",exTh:"",day:1},
{en:"make a commitment to sb/sth",pos:"phr.",th:"ให้คำมั่นสัญญากับ...",ex:"",exTh:"",day:1},
{en:"make a point of",pos:"phr.",th:"ตั้งใจ/ถือเป็นเรื่องสำคัญที่จะ...",ex:"",exTh:"",day:1},
{en:"manpower",pos:"n.",th:"กำลังคน, แรงงาน",ex:"",exTh:"",day:1},
{en:"master's degree",pos:"phr.",th:"ปริญญาโท",ex:"",exTh:"",day:1},
{en:"novice",pos:"n.",th:"มือใหม่, ผู้เริ่มต้น",ex:"",exTh:"",day:1},
{en:"paycheck",pos:"n.",th:"เช็คเงินเดือน/ค่าจ้าง",ex:"",exTh:"",day:1},
{en:"self-motivation",pos:"n.",th:"การสร้างแรงจูงใจให้ตัวเอง",ex:"",exTh:"",day:1},
{en:"send a notification",pos:"phr.",th:"ส่งการแจ้งเตือน",ex:"",exTh:"",day:1},
{en:"vacancy",pos:"n.",th:"ตำแหน่งงานว่าง",ex:"",exTh:"",day:1},
{en:"wanted",pos:"adj.",th:"ที่เป็นที่ต้องการ, ประกาศรับสมัคร",ex:"",exTh:"",day:1},
{en:"work history",pos:"phr.",th:"ประวัติการทำงาน",ex:"",exTh:"",day:1},
/* ===== DAY 02 : กฎหมาย / ระเบียบ ===== */
{en:"bend over",pos:"phr.",th:"ก้มตัวลง, โน้มตัวลง",ex:"",exTh:"",day:2},
{en:"by oneself",pos:"phr.",th:"ด้วยตัวเอง, ตามลำพัง",ex:"",exTh:"",day:2},
{en:"date",pos:"n.",th:"วันที่, การนัดหมาย",ex:"",exTh:"",day:2},
{en:"get used to",pos:"phr.",th:"คุ้นเคยกับ...",ex:"",exTh:"",day:2},
{en:"if it's okay with you",pos:"phr.",th:"ถ้าคุณสะดวก, ถ้าไม่เป็นไรสำหรับคุณ",ex:"",exTh:"",day:2},
{en:"in case of",pos:"phr.",th:"ในกรณีที่...",ex:"",exTh:"",day:2},
{en:"in rows",pos:"phr.",th:"เป็นแถว, เป็นแนว",ex:"",exTh:"",day:2},
{en:"item",pos:"n.",th:"สิ่งของ, รายการ, ชิ้นสินค้า",ex:"",exTh:"",day:2},
{en:"legal",pos:"adj.",th:"ตามกฎหมาย, ถูกกฎหมาย",ex:"",exTh:"",day:2},
{en:"let go",pos:"phr.",th:"ปล่อยไป, ปล่อยวาง",ex:"",exTh:"",day:2},
{en:"ruler",pos:"n.",th:"ไม้บรรทัด, ผู้ปกครอง",ex:"",exTh:"",day:2},
{en:"stop",pos:"v.",th:"หยุด",ex:"",exTh:"",day:2},
{en:"busy",pos:"adj.",th:"ยุ่ง, ไม่ว่าง",ex:"",exTh:"",day:2},
{en:"curriculum",pos:"n.",th:"หลักสูตร",ex:"",exTh:"",day:2},
{en:"dress",pos:"n.",th:"เสื้อผ้า, ชุดกระโปรง",ex:"",exTh:"",day:2},
{en:"enough",pos:"adj.",th:"เพียงพอ",ex:"",exTh:"",day:2},
{en:"finish",pos:"v.",th:"ทำให้เสร็จ, จบ",ex:"",exTh:"",day:2},
{en:"have a problem (in) v-ing",pos:"phr.",th:"มีปัญหากับการ...",ex:"",exTh:"",day:2},
{en:"large",pos:"adj.",th:"ใหญ่",ex:"",exTh:"",day:2},
{en:"law firm",pos:"phr.",th:"บริษัท/สำนักงานกฎหมาย",ex:"",exTh:"",day:2},
{en:"loudly",pos:"adv.",th:"อย่างเสียงดัง",ex:"",exTh:"",day:2},
{en:"plus",pos:"prep.",th:"บวกกับ, รวมกับ",ex:"",exTh:"",day:2},
{en:"protect",pos:"v.",th:"ปกป้อง, คุ้มครอง",ex:"",exTh:"",day:2},
{en:"seldom",pos:"adv.",th:"แทบไม่เคย, ไม่ค่อย",ex:"",exTh:"",day:2},
{en:"theft",pos:"n.",th:"การโจรกรรม, การขโมย",ex:"",exTh:"",day:2},
{en:"try",pos:"v.",th:"พยายาม, ลอง",ex:"",exTh:"",day:2},
{en:"witness",pos:"n.",th:"พยาน",ex:"",exTh:"",day:2},
{en:"write",pos:"v.",th:"เขียน",ex:"",exTh:"",day:2},
{en:"against the law",pos:"phr.",th:"ผิดกฎหมาย, ต่อต้านกฎหมาย",ex:"",exTh:"",day:2},
{en:"by all means",pos:"phr.",th:"แน่นอน, ตามสบาย, ทุกวิถีทาง",ex:"",exTh:"",day:2},
{en:"by mistake",pos:"phr.",th:"โดยไม่ได้ตั้งใจ, โดยบังเอิญ",ex:"",exTh:"",day:2},
{en:"come to an end",pos:"phr.",th:"จบ, สิ้นสุด",ex:"",exTh:"",day:2},
{en:"company regulations",pos:"phr.",th:"กฎระเบียบบริษัท",ex:"",exTh:"",day:2},
{en:"give directions",pos:"phr.",th:"บอกทาง, ให้คำแนะนำ",ex:"",exTh:"",day:2},
{en:"hold up",pos:"phr.",th:"ชูขึ้น, ยกขึ้น",ex:"",exTh:"",day:2},
{en:"if I'm not mistaken",pos:"phr.",th:"ถ้าฉันเข้าใจไม่ผิด",ex:"",exTh:"",day:2},
{en:"in progress",pos:"phr.",th:"กำลังดำเนินการ",ex:"",exTh:"",day:2},
{en:"keep in mind",pos:"phr.",th:"จำไว้ในใจ, คำนึงถึง",ex:"",exTh:"",day:2},
{en:"legal counsel",pos:"phr.",th:"ที่ปรึกษากฎหมาย, ทนายความ",ex:"",exTh:"",day:2},
{en:"self-defense",pos:"n.",th:"การป้องกันตัว",ex:"",exTh:"",day:2},
{en:"suspect",pos:"n.",th:"ผู้ต้องสงสัย",ex:"",exTh:"",day:2},
{en:"take one's advice",pos:"phr.",th:"รับฟังคำแนะนำของ...",ex:"",exTh:"",day:2},
{en:"to one's advantage",pos:"phr.",th:"เพื่อประโยชน์ของ...",ex:"",exTh:"",day:2},
{en:"under control",pos:"phr.",th:"อยู่ในการควบคุม",ex:"",exTh:"",day:2},
{en:"under the supervision of",pos:"phr.",th:"ภายใต้การดูแลของ...",ex:"",exTh:"",day:2},
{en:"abuse",pos:"n.",th:"การใช้ในทางที่ผิด, ทารุณกรรม",ex:"",exTh:"",day:2},
{en:"alert",pos:"v./adj.",th:"เตือน; ตื่นตัว, ระวังภัย",ex:"",exTh:"",day:2},
{en:"assessment",pos:"n.",th:"การประเมิน",ex:"",exTh:"",day:2},
{en:"at all times",pos:"phr.",th:"ตลอดเวลา, ทุกเมื่อ",ex:"",exTh:"",day:2},
{en:"authorization",pos:"n.",th:"การอนุญาต, การมอบอำนาจ",ex:"",exTh:"",day:2},
{en:"concerning",pos:"prep.",th:"เกี่ยวกับ",ex:"",exTh:"",day:2},
{en:"consideration",pos:"n.",th:"การพิจารณา, ความเอาใจใส่",ex:"",exTh:"",day:2},
{en:"defensive",pos:"adj.",th:"เชิงรับ, ป้องกันตัว",ex:"",exTh:"",day:2},
{en:"depiction",pos:"n.",th:"การพรรณนา, การบรรยายภาพ",ex:"",exTh:"",day:2},
{en:"disobedient",pos:"adj.",th:"ไม่เชื่อฟัง, ดื้อ",ex:"",exTh:"",day:2},
{en:"endure",pos:"v.",th:"อดทน, ทนต่อ",ex:"",exTh:"",day:2},
{en:"exemplary",pos:"adj.",th:"เป็นแบบอย่างที่ดี",ex:"",exTh:"",day:2},
{en:"ignore",pos:"v.",th:"เพิกเฉย, ไม่สนใจ",ex:"",exTh:"",day:2},
{en:"illegal",pos:"adj.",th:"ผิดกฎหมาย",ex:"",exTh:"",day:2},
{en:"in accordance with",pos:"phr.",th:"สอดคล้องกับ, เป็นไปตาม",ex:"",exTh:"",day:2},
{en:"indecisive",pos:"adj.",th:"ลังเล, ตัดสินใจไม่ได้",ex:"",exTh:"",day:2},
{en:"justly",pos:"adv.",th:"อย่างยุติธรรม",ex:"",exTh:"",day:2},
{en:"obey",pos:"v.",th:"เชื่อฟัง, ปฏิบัติตาม",ex:"",exTh:"",day:2},
{en:"observance",pos:"n.",th:"การปฏิบัติตาม (กฎ)",ex:"",exTh:"",day:2},
{en:"on-site",pos:"adj.",th:"อยู่ที่หน้างาน, ในสถานที่จริง",ex:"",exTh:"",day:2},
{en:"penalty",pos:"n.",th:"การลงโทษ, ค่าปรับ",ex:"",exTh:"",day:2},
{en:"pointed",pos:"adj.",th:"แหลมคม, ตรงประเด็น",ex:"",exTh:"",day:2},
{en:"precious",pos:"adj.",th:"มีค่า, ล้ำค่า",ex:"",exTh:"",day:2},
{en:"principle",pos:"n.",th:"หลักการ",ex:"",exTh:"",day:2},
{en:"punishment",pos:"n.",th:"การลงโทษ",ex:"",exTh:"",day:2},
{en:"regulate",pos:"v.",th:"ควบคุม, กำกับดูแล",ex:"",exTh:"",day:2},
{en:"restricted area",pos:"phr.",th:"เขตหวงห้าม",ex:"",exTh:"",day:2},
{en:"restriction",pos:"n.",th:"การจำกัด, ข้อจำกัด",ex:"",exTh:"",day:2},
{en:"safety inspection",pos:"phr.",th:"การตรวจสอบความปลอดภัย",ex:"",exTh:"",day:2},
{en:"suppress",pos:"v.",th:"ปราบปราม, ระงับ",ex:"",exTh:"",day:2},
{en:"tensely",pos:"adv.",th:"อย่างตึงเครียด",ex:"",exTh:"",day:2},
{en:"unauthorized",pos:"adj.",th:"ที่ไม่ได้รับอนุญาต",ex:"",exTh:"",day:2},
{en:"accuse",pos:"v.",th:"กล่าวหา",ex:"",exTh:"",day:2},
{en:"assess",pos:"v.",th:"ประเมิน",ex:"",exTh:"",day:2},
{en:"attorney",pos:"n.",th:"ทนายความ",ex:"",exTh:"",day:2},
{en:"be absent from",pos:"phr.",th:"ขาดจาก..., ไม่อยู่ใน...",ex:"",exTh:"",day:2},
{en:"be allowed to do",pos:"phr.",th:"ได้รับอนุญาตให้ทำ...",ex:"",exTh:"",day:2},
{en:"by way of",pos:"phr.",th:"โดยผ่าน, โดยวิธี",ex:"",exTh:"",day:2},
{en:"distrust",pos:"v.",th:"ไม่ไว้วางใจ, คลางแคลงใจ",ex:"",exTh:"",day:2},
{en:"from this day onward",pos:"phr.",th:"ตั้งแต่วันนี้เป็นต้นไป",ex:"",exTh:"",day:2},
{en:"have permission to do",pos:"phr.",th:"ได้รับอนุญาตให้ทำ...",ex:"",exTh:"",day:2},
{en:"in a strict way",pos:"phr.",th:"อย่างเข้มงวด (= strictly)",ex:"",exTh:"",day:2},
{en:"make clear",pos:"phr.",th:"ทำให้ชัดเจน",ex:"",exTh:"",day:2},
{en:"ministry",pos:"n.",th:"กระทรวง",ex:"",exTh:"",day:2},
{en:"newly established",pos:"phr.",th:"ที่เพิ่งก่อตั้งใหม่",ex:"",exTh:"",day:2},
{en:"put into effect",pos:"phr.",th:"นำมาใช้, ทำให้มีผลบังคับ",ex:"",exTh:"",day:2},
{en:"registration confirmation",pos:"phr.",th:"การยืนยันการลงทะเบียน",ex:"",exTh:"",day:2},
{en:"stand over",pos:"phr.",th:"เฝ้าจับตามอง, ยืนคุม",ex:"",exTh:"",day:2},
/* ===== DAY 03 : ในออฟฟิศ / ทั่วไป ===== */
{en:"a sheet of",pos:"phr.",th:"แผ่น (กระดาษ) หนึ่งแผ่น",ex:"",exTh:"",day:3},
{en:"business card",pos:"phr.",th:"นามบัตรธุรกิจ",ex:"",exTh:"",day:3},
{en:"cartridge",pos:"n.",th:"ตลับหมึกพิมพ์",ex:"",exTh:"",day:3},
{en:"daily",pos:"adj.",th:"รายวัน, ประจำวัน",ex:"",exTh:"",day:3},
{en:"edit",pos:"v.",th:"แก้ไข, เรียบเรียง",ex:"",exTh:"",day:3},
{en:"hand",pos:"n.",th:"มือ",ex:"",exTh:"",day:3},
{en:"in order to do",pos:"phr.",th:"เพื่อที่จะ...",ex:"",exTh:"",day:3},
{en:"laptop",pos:"n.",th:"แล็ปท็อป, คอมพิวเตอร์พกพา",ex:"",exTh:"",day:3},
{en:"name tag",pos:"phr.",th:"ป้ายชื่อ",ex:"",exTh:"",day:3},
{en:"on vacation",pos:"phr.",th:"ในช่วงลาพักร้อน",ex:"",exTh:"",day:3},
{en:"paper jam",pos:"phr.",th:"กระดาษติดในเครื่องพิมพ์",ex:"",exTh:"",day:3},
{en:"paperwork",pos:"n.",th:"งานเอกสาร",ex:"",exTh:"",day:3},
{en:"partition",pos:"n.",th:"ฉากกั้น, การแบ่งพื้นที่",ex:"",exTh:"",day:3},
{en:"rush hour",pos:"phr.",th:"ชั่วโมงเร่งด่วน",ex:"",exTh:"",day:3},
{en:"section",pos:"n.",th:"ส่วน, แผนก",ex:"",exTh:"",day:3},
{en:"sheet",pos:"n.",th:"แผ่น, ผ้าปูที่นอน",ex:"",exTh:"",day:3},
{en:"tabletop",pos:"n.",th:"หน้าโต๊ะ, ผิวโต๊ะ",ex:"",exTh:"",day:3},
{en:"telephone call",pos:"phr.",th:"การโทรศัพท์",ex:"",exTh:"",day:3},
{en:"trash bin",pos:"phr.",th:"ถังขยะ",ex:"",exTh:"",day:3},
{en:"upstairs",pos:"adv.",th:"ชั้นบน, ข้างบน",ex:"",exTh:"",day:3},
{en:"as if",pos:"phr.",th:"ราวกับว่า",ex:"",exTh:"",day:3},
{en:"as well as",pos:"phr.",th:"เช่นเดียวกับ, รวมไปถึง",ex:"",exTh:"",day:3},
{en:"be aware of",pos:"phr.",th:"ตระหนักถึง, รู้ถึง...",ex:"",exTh:"",day:3},
{en:"be known as",pos:"phr.",th:"เป็นที่รู้จักในนามว่า...",ex:"",exTh:"",day:3},
{en:"be likely to",pos:"phr.",th:"มีแนวโน้มที่จะ...",ex:"",exTh:"",day:3},
{en:"detail",pos:"n.",th:"รายละเอียด",ex:"",exTh:"",day:3},
{en:"offering",pos:"n.",th:"การเสนอ, สิ่งที่นำเสนอ",ex:"",exTh:"",day:3},
{en:"on one's own",pos:"phr.",th:"ด้วยตัวเอง, ตามลำพัง",ex:"",exTh:"",day:3},
{en:"adjust the mirror",pos:"phr.",th:"ปรับกระจก",ex:"",exTh:"",day:3},
{en:"advance reservation",pos:"phr.",th:"การจองล่วงหน้า",ex:"",exTh:"",day:3},
{en:"arrange an appointment",pos:"phr.",th:"จัดการนัดหมาย, นัดพบ",ex:"",exTh:"",day:3},
{en:"bulletin board",pos:"phr.",th:"กระดานติดประกาศ, บอร์ดประชาสัมพันธ์",ex:"",exTh:"",day:3},
{en:"call back",pos:"phr.",th:"โทรกลับ",ex:"",exTh:"",day:3},
{en:"confused",pos:"adj.",th:"สับสน, งุนงง",ex:"",exTh:"",day:3},
{en:"errand",pos:"n.",th:"ธุระที่ให้ไปทำ",ex:"",exTh:"",day:3},
{en:"extend an invitation",pos:"phr.",th:"เชิญ, ยื่นคำเชิญ",ex:"",exTh:"",day:3},
{en:"get a permit",pos:"phr.",th:"ขอ/ได้ใบอนุญาต",ex:"",exTh:"",day:3},
{en:"hand in",pos:"phr.",th:"ส่ง, ยื่น (เอกสาร)",ex:"",exTh:"",day:3},
{en:"have a day off",pos:"phr.",th:"หยุดงานหนึ่งวัน",ex:"",exTh:"",day:3},
{en:"have a long day",pos:"phr.",th:"เหนื่อยทั้งวัน, มีวันที่ยาวนาน",ex:"",exTh:"",day:3},
{en:"head up",pos:"phr.",th:"เป็นหัวหน้า, นำ, รับผิดชอบ",ex:"",exTh:"",day:3},
{en:"in a hurry",pos:"phr.",th:"รีบเร่ง, รีบร้อน",ex:"",exTh:"",day:3},
{en:"in alphabetical order",pos:"phr.",th:"เรียงตามลำดับตัวอักษร",ex:"",exTh:"",day:3},
{en:"in luck",pos:"phr.",th:"โชคดี",ex:"",exTh:"",day:3},
{en:"leave A up to B",pos:"phr.",th:"ปล่อยให้ B จัดการ A",ex:"",exTh:"",day:3},
{en:"leave A with B",pos:"phr.",th:"ฝาก A ไว้กับ B",ex:"",exTh:"",day:3},
{en:"listing",pos:"n.",th:"รายการ",ex:"",exTh:"",day:3},
{en:"make a call",pos:"phr.",th:"โทรศัพท์หา",ex:"",exTh:"",day:3},
{en:"make a correction",pos:"phr.",th:"แก้ไข",ex:"",exTh:"",day:3},
{en:"make a final change",pos:"phr.",th:"เปลี่ยนแปลงครั้งสุดท้าย",ex:"",exTh:"",day:3},
{en:"make a note of",pos:"phr.",th:"จดบันทึก...",ex:"",exTh:"",day:3},
{en:"make an impression",pos:"phr.",th:"สร้างความประทับใจ",ex:"",exTh:"",day:3},
{en:"move ahead with",pos:"phr.",th:"ดำเนินการต่อ, เดินหน้าต่อ",ex:"",exTh:"",day:3},
{en:"on a business trip",pos:"phr.",th:"เดินทางไปทำงาน/ธุระต่างจังหวัด",ex:"",exTh:"",day:3},
{en:"on a weekly basis",pos:"phr.",th:"เป็นประจำทุกสัปดาห์",ex:"",exTh:"",day:3},
{en:"on business",pos:"phr.",th:"ในเรื่องงาน, เพื่อทำธุรกิจ",ex:"",exTh:"",day:3},
{en:"on duty",pos:"phr.",th:"เข้าเวร, ปฏิบัติหน้าที่",ex:"",exTh:"",day:3},
{en:"pick up the phone",pos:"phr.",th:"รับโทรศัพท์",ex:"",exTh:"",day:3},
{en:"scrub",pos:"v.",th:"ขัดถู",ex:"",exTh:"",day:3},
{en:"seal",pos:"n./v.",th:"ตราประทับ, ปิดผนึก",ex:"",exTh:"",day:3},
{en:"speak into the microphone",pos:"phr.",th:"พูดใส่ไมโครโฟน",ex:"",exTh:"",day:3},
{en:"speak on the phone",pos:"phr.",th:"คุยโทรศัพท์",ex:"",exTh:"",day:3},
{en:"stand in a line",pos:"phr.",th:"ยืนเข้าแถว",ex:"",exTh:"",day:3},
{en:"take a message",pos:"phr.",th:"รับ/จดข้อความ",ex:"",exTh:"",day:3},
{en:"take apart",pos:"phr.",th:"ถอด/แยกชิ้นส่วน",ex:"",exTh:"",day:3},
{en:"utility provider",pos:"phr.",th:"ผู้ให้บริการสาธารณูปโภค",ex:"",exTh:"",day:3},
{en:"acquired",pos:"adj.",th:"ที่ได้มา, ที่ได้รับมา",ex:"",exTh:"",day:3},
{en:"adapt",pos:"v.",th:"ปรับตัว, ดัดแปลง",ex:"",exTh:"",day:3},
{en:"administer",pos:"v.",th:"บริหาร, จัดการ, ปกครอง",ex:"",exTh:"",day:3},
{en:"clerical",pos:"adj.",th:"เกี่ยวกับงานเอกสาร/เสมียน",ex:"",exTh:"",day:3},
{en:"conclusive",pos:"adj.",th:"ที่สรุปได้แน่ชัด, เด็ดขาด",ex:"",exTh:"",day:3},
{en:"delete",pos:"v.",th:"ลบ",ex:"",exTh:"",day:3},
{en:"editorial",pos:"adj.",th:"เกี่ยวกับบรรณาธิการ",ex:"",exTh:"",day:3},
{en:"endless",pos:"adj.",th:"ไม่มีที่สิ้นสุด, ไม่รู้จบ",ex:"",exTh:"",day:3},
{en:"furthermore",pos:"adv.",th:"ยิ่งไปกว่านั้น, นอกจากนี้",ex:"",exTh:"",day:3},
{en:"in one's absence",pos:"phr.",th:"ในช่วงที่...ไม่อยู่",ex:"",exTh:"",day:3},
{en:"on purpose",pos:"phr.",th:"โดยตั้งใจ, โดยเจตนา",ex:"",exTh:"",day:3},
{en:"overseas",pos:"adj./adv.",th:"ต่างประเทศ, ในต่างประเทศ",ex:"",exTh:"",day:3},
{en:"perceive",pos:"v.",th:"รับรู้, เข้าใจ, สังเกตเห็น",ex:"",exTh:"",day:3},
{en:"reminder",pos:"n.",th:"เครื่องเตือนใจ, สิ่งที่เตือนความจำ",ex:"",exTh:"",day:3},
{en:"roughly",pos:"adv.",th:"อย่างคร่าวๆ, ประมาณ",ex:"",exTh:"",day:3},
{en:"strive",pos:"v.",th:"พยายามอย่างหนัก, มุ่งมั่น",ex:"",exTh:"",day:3},
{en:"translate",pos:"v.",th:"แปล",ex:"",exTh:"",day:3},
{en:"boardroom",pos:"n.",th:"ห้องประชุมคณะกรรมการ",ex:"",exTh:"",day:3},
{en:"in person",pos:"phr.",th:"ด้วยตนเอง, ต่อหน้า",ex:"",exTh:"",day:3},
{en:"including",pos:"prep.",th:"รวมถึง",ex:"",exTh:"",day:3},
{en:"on time",pos:"phr.",th:"ตรงเวลา",ex:"",exTh:"",day:3},
{en:"panic",pos:"n.",th:"อาการตื่นตระหนก",ex:"",exTh:"",day:3},
{en:"past due",pos:"phr.",th:"เกินกำหนด, เลยกำหนดชำระ",ex:"",exTh:"",day:3},
{en:"put forward",pos:"phr.",th:"เสนอ, เสนอความคิดเห็น",ex:"",exTh:"",day:3},
{en:"regard A as B",pos:"phr.",th:"ถือว่า A เป็น B",ex:"",exTh:"",day:3},
{en:"return one's call",pos:"phr.",th:"โทรกลับหา...",ex:"",exTh:"",day:3},
{en:"secretarial",pos:"adj.",th:"เกี่ยวกับงานเลขานุการ",ex:"",exTh:"",day:3},
{en:"take charge of",pos:"phr.",th:"ดูแลรับผิดชอบ",ex:"",exTh:"",day:3},
/* ===== DAY 04 : ในออฟฟิศ / เครื่องใช้สำนักงาน ===== */
{en:"bookcase",pos:"n.",th:"ตู้หนังสือ",ex:"",exTh:"",day:4},
{en:"bookshelf",pos:"n.",th:"ชั้นวางหนังสือ",ex:"",exTh:"",day:4},
{en:"case",pos:"n.",th:"กรณี, สถานการณ์",ex:"",exTh:"",day:4},
{en:"central office",pos:"phr.",th:"สำนักงานกลาง",ex:"",exTh:"",day:4},
{en:"copy machine",pos:"phr.",th:"เครื่องถ่ายเอกสาร",ex:"",exTh:"",day:4},
{en:"fax",pos:"n.",th:"แฟกซ์, เครื่องโทรสาร",ex:"",exTh:"",day:4},
{en:"file folder",pos:"phr.",th:"แฟ้มเอกสาร",ex:"",exTh:"",day:4},
{en:"greet",pos:"v.",th:"ทักทาย",ex:"",exTh:"",day:4},
{en:"handwriting",pos:"n.",th:"ลายมือ",ex:"",exTh:"",day:4},
{en:"keypad",pos:"n.",th:"แผงแป้นพิมพ์",ex:"",exTh:"",day:4},
{en:"knife",pos:"n.",th:"มีด",ex:"",exTh:"",day:4},
{en:"log on to",pos:"phr.",th:"ลงชื่อเข้าใช้บริการ",ex:"",exTh:"",day:4},
{en:"online",pos:"adj./adv.",th:"ออนไลน์, ที่ใช้อินเทอร์เน็ต",ex:"",exTh:"",day:4},
{en:"photocopier",pos:"n.",th:"เครื่องถ่ายเอกสาร",ex:"",exTh:"",day:4},
{en:"photocopy",pos:"n./v.",th:"เอกสารสำเนา; ถ่ายสำเนา",ex:"",exTh:"",day:4},
{en:"print out",pos:"phr.",th:"พิมพ์ออกมา",ex:"",exTh:"",day:4},
{en:"right away",pos:"phr.",th:"ทันที",ex:"",exTh:"",day:4},
{en:"spell",pos:"v.",th:"สะกด (ตัวอักษร)",ex:"",exTh:"",day:4},
{en:"wrap",pos:"v.",th:"ห่อ, พัน",ex:"",exTh:"",day:4},
{en:"fold",pos:"v.",th:"ม้วน, พับ",ex:"",exTh:"",day:4},
{en:"least",pos:"adj.",th:"น้อยที่สุด, อย่างต่ำ",ex:"",exTh:"",day:4},
{en:"paper",pos:"n.",th:"กระดาษ",ex:"",exTh:"",day:4},
{en:"planning",pos:"n.",th:"การวางแผน",ex:"",exTh:"",day:4},
{en:"post",pos:"v.",th:"ลงข้อความ/สื่อบนอินเทอร์เน็ต",ex:"",exTh:"",day:4},
{en:"press the button",pos:"phr.",th:"กดปุ่ม",ex:"",exTh:"",day:4},
{en:"server",pos:"n.",th:"เซิร์ฟเวอร์, โปรแกรมบริการ",ex:"",exTh:"",day:4},
{en:"store opening",pos:"phr.",th:"การเปิดร้าน",ex:"",exTh:"",day:4},
{en:"task",pos:"n.",th:"งาน, หน้าที่",ex:"",exTh:"",day:4},
{en:"be satisfied with",pos:"phr.",th:"รู้สึกพอใจ",ex:"",exTh:"",day:4},
{en:"be seated",pos:"phr.",th:"นั่งลง",ex:"",exTh:"",day:4},
{en:"be surrounded by",pos:"phr.",th:"โอบล้อมไปด้วย",ex:"",exTh:"",day:4},
{en:"business contacts",pos:"phr.",th:"ข้อมูลผู้ติดต่อทางธุรกิจ",ex:"",exTh:"",day:4},
{en:"chairperson",pos:"n.",th:"ประธานบริษัท",ex:"",exTh:"",day:4},
{en:"copy editor",pos:"phr.",th:"บรรณาธิการตรวจแก้",ex:"",exTh:"",day:4},
{en:"deep end",pos:"phr.",th:"สถานการณ์ลำบากที่ไม่ทันตั้งตัว",ex:"",exTh:"",day:4},
{en:"double-sided",pos:"adj.",th:"ใช้งานได้ทั้งสองด้าน",ex:"",exTh:"",day:4},
{en:"drawer",pos:"n.",th:"ลิ้นชัก",ex:"",exTh:"",day:4},
{en:"get one's approval",pos:"phr.",th:"ขออนุญาตจาก...",ex:"",exTh:"",day:4},
{en:"halfway",pos:"adv.",th:"ซึ่งดำเนินไปครึ่งทางแล้ว",ex:"",exTh:"",day:4},
{en:"hand over",pos:"phr.",th:"ส่ง, มอบ, ยื่นให้",ex:"",exTh:"",day:4},
{en:"in a pile",pos:"phr.",th:"เป็นกอง, เป็นตั้ง",ex:"",exTh:"",day:4},
{en:"it could have been worse",pos:"phr.",th:"แย่กว่านี้ก็ยังได้ (ยังไม่แย่ที่สุด)",ex:"",exTh:"",day:4},
{en:"just in time",pos:"phr.",th:"ทันเวลาพอดี",ex:"",exTh:"",day:4},
{en:"literacy",pos:"n.",th:"การรู้หนังสือ, ความสามารถอ่านออกเขียนได้",ex:"",exTh:"",day:4},
{en:"litter",pos:"n./v.",th:"ขยะ; ทิ้งขยะเกลื่อนกลาด",ex:"",exTh:"",day:4},
{en:"make a selection",pos:"phr.",th:"คัด, เลือกสรร",ex:"",exTh:"",day:4},
{en:"make room for",pos:"phr.",th:"หาพื้นที่ว่างสำหรับ",ex:"",exTh:"",day:4},
{en:"out of paper",pos:"phr.",th:"กระดาษหมด",ex:"",exTh:"",day:4},
{en:"raise one's hand",pos:"phr.",th:"ยกมือ",ex:"",exTh:"",day:4},
{en:"report a problem",pos:"phr.",th:"แจ้ง/รายงานปัญหา",ex:"",exTh:"",day:4},
{en:"sort",pos:"n./v.",th:"ประเภท, ชนิด; แยกประเภท",ex:"",exTh:"",day:4},
{en:"stationery",pos:"n.",th:"อุปกรณ์เครื่องเขียน",ex:"",exTh:"",day:4},
{en:"take another look",pos:"phr.",th:"ดู/ตรวจตราอีกครั้ง",ex:"",exTh:"",day:4},
{en:"take A out",pos:"phr.",th:"พา...ออกไป, เอา...ออก",ex:"",exTh:"",day:4},
{en:"typewriter",pos:"n.",th:"เครื่องพิมพ์ดีด",ex:"",exTh:"",day:4},
{en:"work in groups",pos:"phr.",th:"ทำงานเป็นกลุ่ม",ex:"",exTh:"",day:4},
{en:"writing pad",pos:"phr.",th:"กระดาษสำหรับเขียน",ex:"",exTh:"",day:4},
{en:"anticipation",pos:"n.",th:"ความคาดหวัง",ex:"",exTh:"",day:4},
{en:"automobile",pos:"n.",th:"ยานยนต์",ex:"",exTh:"",day:4},
{en:"be asked to do",pos:"phr.",th:"ถูกขอร้องให้ทำ...",ex:"",exTh:"",day:4},
{en:"be paid for",pos:"phr.",th:"ได้รับค่าจ้างจาก...",ex:"",exTh:"",day:4},
{en:"be qualified for",pos:"phr.",th:"มีคุณสมบัติสำหรับ...",ex:"",exTh:"",day:4},
{en:"casual",pos:"adj.",th:"ที่ไม่เป็นทางการ, สบายๆ",ex:"",exTh:"",day:4},
{en:"draft",pos:"n./v.",th:"เอกสารฉบับร่าง; ร่างเอกสาร",ex:"",exTh:"",day:4},
{en:"draw on",pos:"phr.",th:"(เวลา) ผ่านพ้นไป; ใช้ (สิ่งที่มี)",ex:"",exTh:"",day:4},
{en:"excuse",pos:"n./v.",th:"ข้ออ้าง; อ้างเหตุผล",ex:"",exTh:"",day:4},
{en:"head office",pos:"phr.",th:"สำนักงานใหญ่",ex:"",exTh:"",day:4},
{en:"in anticipation of",pos:"phr.",th:"ในความคาดหวังเกี่ยวกับ...",ex:"",exTh:"",day:4},
{en:"in light of",pos:"phr.",th:"หลังจากพิจารณา...",ex:"",exTh:"",day:4},
{en:"instrument",pos:"n.",th:"เครื่องมือ, เครื่องดนตรี",ex:"",exTh:"",day:4},
{en:"popularly",pos:"adv.",th:"โดยคนหมู่มาก, อย่างกว้างขวาง",ex:"",exTh:"",day:4},
{en:"regarding",pos:"prep.",th:"เกี่ยวกับ",ex:"",exTh:"",day:4},
{en:"routinely",pos:"adv.",th:"เป็นกิจวัตร, เป็นประจำ",ex:"",exTh:"",day:4},
{en:"standing",pos:"adj.",th:"ถาวร, คงที่",ex:"",exTh:"",day:4},
{en:"supplementary",pos:"adj.",th:"ที่เพิ่มเติม, ที่เสริมเข้ามา",ex:"",exTh:"",day:4},
{en:"work overtime",pos:"phr.",th:"ทำงานล่วงเวลา",ex:"",exTh:"",day:4},
{en:"workplace",pos:"n.",th:"ที่ทำงาน",ex:"",exTh:"",day:4},
{en:"acting",pos:"adj./n.",th:"ที่ทำหน้าที่แทน (ชั่วคราว); การแสดง",ex:"",exTh:"",day:4},
{en:"be full of",pos:"phr.",th:"เต็มไปด้วย",ex:"",exTh:"",day:4},
{en:"convert A to B",pos:"phr.",th:"เปลี่ยนจาก...เป็น...",ex:"",exTh:"",day:4},
{en:"count on",pos:"phr.",th:"พึ่งพา, ไว้ใจ",ex:"",exTh:"",day:4},
{en:"fill with",pos:"phr.",th:"เติม/กรอกด้วย...",ex:"",exTh:"",day:4},
{en:"get along with",pos:"phr.",th:"เข้ากันได้ดีกับ...",ex:"",exTh:"",day:4},
{en:"go down the steps",pos:"phr.",th:"เดินลงบันได",ex:"",exTh:"",day:4},
{en:"key to success",pos:"phr.",th:"สิ่งสำคัญที่นำไปสู่ความสำเร็จ",ex:"",exTh:"",day:4},
{en:"lose one's temper",pos:"phr.",th:"อารมณ์เสีย, โมโห",ex:"",exTh:"",day:4},
{en:"make a copy",pos:"phr.",th:"ถ่ายสำเนา",ex:"",exTh:"",day:4},
{en:"obsess about",pos:"phr.",th:"หมกมุ่น, พูดซ้ำๆ ซากๆ",ex:"",exTh:"",day:4},
{en:"overtime hours",pos:"phr.",th:"ชั่วโมงนอกเวลางาน",ex:"",exTh:"",day:4},
{en:"personal effects",pos:"phr.",th:"ทรัพย์สินส่วนตัว",ex:"",exTh:"",day:4},
{en:"reunion",pos:"n.",th:"งานเลี้ยงคืนสู่เหย้า, การพบกันใหม่",ex:"",exTh:"",day:4},
{en:"sales representative",pos:"phr.",th:"พนักงานขาย",ex:"",exTh:"",day:4},
{en:"seamless",pos:"adj.",th:"ต่อเนื่อง, ไร้รอยต่อ",ex:"",exTh:"",day:4},
{en:"submit A to B",pos:"phr.",th:"ยื่น A ต่อ B; ทำให้ A อยู่ใต้ B",ex:"",exTh:"",day:4},
{en:"succeed in",pos:"phr.",th:"ประสบความสำเร็จใน...",ex:"",exTh:"",day:4},
{en:"time-consuming",pos:"adj.",th:"ที่กินเวลานานมาก",ex:"",exTh:"",day:4},
{en:"bookkeeping",pos:"n.",th:"การทำบัญชี",ex:"",exTh:"",day:4},
{en:"have one's hands full",pos:"phr.",th:"ยุ่งมาก",ex:"",exTh:"",day:4},
{en:"make an outside call",pos:"phr.",th:"โทรศัพท์หาคน/บริษัทภายนอก",ex:"",exTh:"",day:4},
{en:"motivation",pos:"n.",th:"แรงจูงใจ, สิ่งจูงใจ",ex:"",exTh:"",day:4},
{en:"newly listed",pos:"phr.",th:"ที่เพิ่งลงรายการใหม่ๆ",ex:"",exTh:"",day:4},
{en:"prioritize",pos:"v.",th:"จัดลำดับความสำคัญ",ex:"",exTh:"",day:4},
{en:"sit in alternate seats",pos:"phr.",th:"นั่งสลับที่/นั่งเว้นที่",ex:"",exTh:"",day:4},
{en:"written authorization",pos:"phr.",th:"การมอบอำนาจเป็นลายลักษณ์อักษร",ex:"",exTh:"",day:4},
{en:"written consent",pos:"phr.",th:"การยินยอมเป็นลายลักษณ์อักษร",ex:"",exTh:"",day:4},
{en:"acquaintance",pos:"n.",th:"คนรู้จัก",ex:"",exTh:"",day:4},
{en:"dimension",pos:"n.",th:"มิติ, มุมมอง",ex:"",exTh:"",day:4},
{en:"directive",pos:"adj.",th:"ซึ่งเป็นการชี้แจง/แนะแนวทาง",ex:"",exTh:"",day:4},
{en:"discerning",pos:"adj.",th:"มีวิสัยทัศน์, มองการณ์ไกล",ex:"",exTh:"",day:4},
{en:"elegantly",pos:"adv.",th:"อย่างสง่างาม, อย่างหรูหรา",ex:"",exTh:"",day:4},
{en:"expectant",pos:"adj.",th:"ที่คาดหวังไว้; ตั้งท้อง",ex:"",exTh:"",day:4},
{en:"invaluable",pos:"adj.",th:"มีประโยชน์มากๆ, ประเมินค่าไม่ได้",ex:"",exTh:"",day:4},
{en:"propel",pos:"v.",th:"ขับเคลื่อน",ex:"",exTh:"",day:4},
{en:"realization",pos:"n.",th:"การตระหนักรู้; การทำให้สำเร็จ",ex:"",exTh:"",day:4},
{en:"recline",pos:"v.",th:"เอนหลัง",ex:"",exTh:"",day:4},
{en:"repository",pos:"n.",th:"โกดัง, คลัง",ex:"",exTh:"",day:4},
{en:"respective",pos:"adj.",th:"แต่ละ, ของแต่ละคน/สิ่ง",ex:"",exTh:"",day:4},
{en:"spontaneously",pos:"adv.",th:"โดยธรรมชาติ/สัญชาตญาณ, โดยอัตโนมัติ",ex:"",exTh:"",day:4},
{en:"trivial",pos:"adj.",th:"เล็กน้อย, ไม่สำคัญ",ex:"",exTh:"",day:4},
{en:"turn in",pos:"phr.",th:"ส่งงาน",ex:"",exTh:"",day:4},
{en:"ambiance",pos:"n.",th:"บรรยากาศ (= ambience)",ex:"",exTh:"",day:4},
{en:"aspiration",pos:"n.",th:"ความทะเยอทะยาน",ex:"",exTh:"",day:4},
{en:"creditable",pos:"adj.",th:"น่าเชื่อถือ",ex:"",exTh:"",day:4},
{en:"eminent",pos:"adj.",th:"โดดเด่น, ชัดเจน",ex:"",exTh:"",day:4},
{en:"endeavor",pos:"n.",th:"ความพยายาม",ex:"",exTh:"",day:4},
{en:"entrust A with B",pos:"phr.",th:"มอบหมายงาน...ให้...ทำ",ex:"",exTh:"",day:4},
{en:"on edge",pos:"phr.",th:"ประหม่า, ตื่นเต้น, โกรธง่าย",ex:"",exTh:"",day:4},
{en:"reach one's full potential",pos:"phr.",th:"ใช้ศักยภาพที่มีจนถึงขีดสุด",ex:"",exTh:"",day:4},
/* ===== DAY 05 : ในออฟฟิศ (3) ===== */
{en:"briefcase",pos:"n.",th:"กระเป๋าเอกสาร",ex:"",exTh:"",day:5},
{en:"business trip",pos:"phr.",th:"การเดินทางไปทำธุรกิจ",ex:"",exTh:"",day:5},
{en:"come over",pos:"phr.",th:"เดินทางมา, แวะมา",ex:"",exTh:"",day:5},
{en:"counter",pos:"n./adj.",th:"เคาน์เตอร์; ตรงกันข้าม",ex:"",exTh:"",day:5},
{en:"e-mail",pos:"n.",th:"จดหมายอิเล็กทรอนิกส์, อีเมล",ex:"",exTh:"",day:5},
{en:"filing cabinet",pos:"phr.",th:"ตู้เก็บเอกสาร",ex:"",exTh:"",day:5},
{en:"folder",pos:"n.",th:"แฟ้มใส่เอกสาร",ex:"",exTh:"",day:5},
{en:"headache",pos:"n.",th:"อาการปวดศีรษะ",ex:"",exTh:"",day:5},
{en:"internship",pos:"n.",th:"การฝึกงาน",ex:"",exTh:"",day:5},
{en:"redo",pos:"v.",th:"ทำหรือแก้ใหม่",ex:"",exTh:"",day:5},
{en:"routine",pos:"n./adj.",th:"กิจวัตร; ที่เกิดขึ้นเป็นประจำ",ex:"",exTh:"",day:5},
{en:"table lamp",pos:"phr.",th:"โคมไฟตั้งโต๊ะ",ex:"",exTh:"",day:5},
{en:"thanks to",pos:"phr.",th:"เนื่องจาก, ต้องขอบคุณ",ex:"",exTh:"",day:5},
{en:"timetable",pos:"n.",th:"ตารางเวลา",ex:"",exTh:"",day:5},
{en:"window display",pos:"phr.",th:"การแสดงสินค้าตัวอย่างในตู้กระจก",ex:"",exTh:"",day:5},
{en:"chief",pos:"adj./n.",th:"สำคัญที่สุด, เป็นอันดับหนึ่ง; หัวหน้า",ex:"",exTh:"",day:5},
{en:"conceal",pos:"v.",th:"ปกปิด",ex:"",exTh:"",day:5},
{en:"correct",pos:"adj./v.",th:"ถูกต้อง; แก้ให้ถูกต้อง",ex:"",exTh:"",day:5},
{en:"economic",pos:"adj.",th:"ที่เกี่ยวกับเศรษฐกิจ",ex:"",exTh:"",day:5},
{en:"embrace",pos:"v.",th:"นำมาใช้, ยอมรับ (โอบกอด)",ex:"",exTh:"",day:5},
{en:"expected",pos:"adj.",th:"ที่คาดหวัง",ex:"",exTh:"",day:5},
{en:"forum",pos:"n.",th:"การประชุม, เวที, สภา",ex:"",exTh:"",day:5},
{en:"instead of",pos:"phr.",th:"แทนที่...",ex:"",exTh:"",day:5},
{en:"mission",pos:"n.",th:"ภารกิจ, งานที่ต้องทำให้เสร็จ",ex:"",exTh:"",day:5},
{en:"programming",pos:"n.",th:"ตารางรายการวิทยุและโทรทัศน์",ex:"",exTh:"",day:5},
{en:"remaining",pos:"adj.",th:"ที่เหลืออยู่",ex:"",exTh:"",day:5},
{en:"rush",pos:"v.",th:"เร่งรีบ",ex:"",exTh:"",day:5},
{en:"unfortunately",pos:"adv.",th:"โชคร้าย, อย่างน่าเสียดาย",ex:"",exTh:"",day:5},
{en:"archive",pos:"n.",th:"เอกสารสำคัญ, ที่เก็บเอกสาร",ex:"",exTh:"",day:5},
{en:"be unwilling to do",pos:"phr.",th:"ไม่เต็มใจที่จะ...",ex:"",exTh:"",day:5},
{en:"be up late",pos:"phr.",th:"นอนดึก, ตื่นดึก",ex:"",exTh:"",day:5},
{en:"blackout",pos:"n.",th:"การเป็นลมหมดสติ; การปิดข่าว; ไฟดับ",ex:"",exTh:"",day:5},
{en:"board meeting",pos:"phr.",th:"การประชุมคณะกรรมการผู้บริหาร",ex:"",exTh:"",day:5},
{en:"board of directors",pos:"phr.",th:"คณะกรรมการผู้บริหาร",ex:"",exTh:"",day:5},
{en:"cross one's arms",pos:"phr.",th:"เอามือกอดอก",ex:"",exTh:"",day:5},
{en:"depressing",pos:"adj.",th:"น่าหดหู่ใจ",ex:"",exTh:"",day:5},
{en:"drag",pos:"v.",th:"ลาก, จูง, กระชาก",ex:"",exTh:"",day:5},
{en:"fold in half",pos:"phr.",th:"พับครึ่ง",ex:"",exTh:"",day:5},
{en:"fold up",pos:"phr.",th:"ม้วน, พับเก็บ",ex:"",exTh:"",day:5},
{en:"frighten",pos:"v.",th:"ทำให้หวาดกลัว",ex:"",exTh:"",day:5},
{en:"keep going",pos:"phr.",th:"ทำต่อไป, ไปต่อ",ex:"",exTh:"",day:5},
{en:"long-term",pos:"adj.",th:"ที่เป็นระยะยาว",ex:"",exTh:"",day:5},
{en:"look up to",pos:"phr.",th:"เคารพ, ยกย่อง",ex:"",exTh:"",day:5},
{en:"make a presentation",pos:"phr.",th:"นำเสนองาน",ex:"",exTh:"",day:5},
{en:"make a revision",pos:"phr.",th:"แก้ไข, ปรับปรุง",ex:"",exTh:"",day:5},
{en:"make an error",pos:"phr.",th:"ทำพลาด",ex:"",exTh:"",day:5},
{en:"meet the deadline",pos:"phr.",th:"ทันวันครบกำหนด",ex:"",exTh:"",day:5},
{en:"meet the requirements",pos:"phr.",th:"มีคุณสมบัติตามที่ต้องการ",ex:"",exTh:"",day:5},
{en:"mess up",pos:"phr.",th:"ทำให้ยุ่งเหยิง, ทำเสียหาย",ex:"",exTh:"",day:5},
{en:"My schedule doesn't permit it.",pos:"phr.",th:"ตารางงานยุ่งเกินไปจนทำไม่ได้",ex:"",exTh:"",day:5},
{en:"obvious",pos:"adj.",th:"ชัดเจน, เห็นได้ชัด",ex:"",exTh:"",day:5},
{en:"office supplies",pos:"phr.",th:"อุปกรณ์ที่ใช้ในสำนักงาน",ex:"",exTh:"",day:5},
{en:"overlook",pos:"v.",th:"มองข้าม; มองลงมา",ex:"",exTh:"",day:5},
{en:"overnight",pos:"adv.",th:"ข้ามคืน",ex:"",exTh:"",day:5},
{en:"papers",pos:"pl.",th:"เอกสาร",ex:"",exTh:"",day:5},
{en:"proofread",pos:"v.",th:"พิสูจน์อักษร",ex:"",exTh:"",day:5},
{en:"rearrange",pos:"v.",th:"เปลี่ยน (วัน/เวลา/สถานที่), จัดใหม่",ex:"",exTh:"",day:5},
{en:"recondition",pos:"v.",th:"ซ่อมแซม, ทำให้กลับสภาพดี",ex:"",exTh:"",day:5},
{en:"rest one's chin on one's hand",pos:"phr.",th:"เท้าคาง",ex:"",exTh:"",day:5},
{en:"stool",pos:"n.",th:"ม้านั่ง (ไม่มีพนัก)",ex:"",exTh:"",day:5},
{en:"timecard",pos:"n.",th:"บัตรตอกเวลางาน",ex:"",exTh:"",day:5},
{en:"wipe",pos:"v.",th:"เช็ด, ถู",ex:"",exTh:"",day:5},
{en:"work additional hours",pos:"phr.",th:"ทำงานล่วงเวลา",ex:"",exTh:"",day:5},
{en:"work shift",pos:"phr.",th:"กะ/ช่วงเวลาเข้างาน",ex:"",exTh:"",day:5},
{en:"burdensome",pos:"adj.",th:"ที่เป็นปัญหาหรือภาระ",ex:"",exTh:"",day:5},
{en:"circulate",pos:"v.",th:"ไหลเวียน, ถ่ายเท, เผยแพร่",ex:"",exTh:"",day:5},
{en:"commend",pos:"v.",th:"ยกย่อง, ชมเชย",ex:"",exTh:"",day:5},
{en:"company",pos:"n.",th:"บริษัท",ex:"",exTh:"",day:5},
{en:"discourage",pos:"v.",th:"ทำให้ท้อแท้, ตัดกำลังใจ",ex:"",exTh:"",day:5},
{en:"distraction",pos:"n.",th:"การเบี่ยงเบน, สิ่งที่ทำให้ไขว้เขว",ex:"",exTh:"",day:5},
{en:"failure",pos:"n.",th:"ความล้มเหลว",ex:"",exTh:"",day:5},
{en:"followed by",pos:"phr.",th:"ตามมาด้วย",ex:"",exTh:"",day:5},
{en:"interruption",pos:"n.",th:"การรบกวน, การขัดจังหวะ",ex:"",exTh:"",day:5},
{en:"make sure",pos:"phr.",th:"ทำให้มั่นใจ, ไม่ลืมที่จะ...",ex:"",exTh:"",day:5},
{en:"mislabeled",pos:"adj.",th:"ที่ติดป้าย/ฉลากผิด",ex:"",exTh:"",day:5},
{en:"observant",pos:"adj.",th:"ช่างสังเกต; เคร่งครัด (ศาสนา)",ex:"",exTh:"",day:5},
{en:"persuade",pos:"v.",th:"ชักชวน, หว่านล้อม, โน้มน้าว",ex:"",exTh:"",day:5},
{en:"proposed",pos:"adj.",th:"ที่ยื่นเสนอ",ex:"",exTh:"",day:5},
{en:"rephrase",pos:"v.",th:"เรียบเรียงใหม่, พูดใหม่",ex:"",exTh:"",day:5},
{en:"scarcely",pos:"adv.",th:"แทบจะไม่",ex:"",exTh:"",day:5},
{en:"concisely",pos:"adv.",th:"อย่างสั้นกระชับ",ex:"",exTh:"",day:5},
{en:"disapproval",pos:"n.",th:"การไม่อนุญาต, การไม่ยอมรับ",ex:"",exTh:"",day:5},
{en:"disapprove",pos:"v.",th:"ไม่อนุญาต, ไม่เห็นด้วย",ex:"",exTh:"",day:5},
{en:"do A a favor",pos:"phr.",th:"ช่วยทำบางสิ่งให้...",ex:"",exTh:"",day:5},
{en:"do a good job",pos:"phr.",th:"ทำได้ดี, เก่ง",ex:"",exTh:"",day:5},
{en:"draw a distinction between",pos:"phr.",th:"ระบุความแตกต่างระหว่าง...",ex:"",exTh:"",day:5},
{en:"exposed",pos:"adj.",th:"ไม่มีที่ปิดบัง, ไม่มั่นคง",ex:"",exTh:"",day:5},
{en:"intensive",pos:"adj.",th:"เข้มข้น",ex:"",exTh:"",day:5},
{en:"problematic",pos:"adj.",th:"ที่เป็นปัญหา",ex:"",exTh:"",day:5},
{en:"project coordinator",pos:"phr.",th:"ผู้ประสานงานโครงการ",ex:"",exTh:"",day:5},
{en:"project management",pos:"phr.",th:"การจัดการ/บริหารโครงการ",ex:"",exTh:"",day:5},
{en:"seating capacity",pos:"phr.",th:"ความจุที่นั่ง",ex:"",exTh:"",day:5},
{en:"take care of",pos:"phr.",th:"ดูแล, ใส่ใจ",ex:"",exTh:"",day:5},
{en:"take on",pos:"phr.",th:"รับทำ, เริ่ม, จ้างงาน",ex:"",exTh:"",day:5},
{en:"tremendous",pos:"adj.",th:"ใหญ่โต, มโหฬาร",ex:"",exTh:"",day:5},
{en:"under the new management",pos:"phr.",th:"ภายใต้ผู้บริหารงานใหม่",ex:"",exTh:"",day:5},
{en:"astute",pos:"adj.",th:"ฉลาด, มีไหวพริบ",ex:"",exTh:"",day:5},
{en:"bring along",pos:"phr.",th:"นำมาด้วย, ก่อให้เกิด",ex:"",exTh:"",day:5},
{en:"compartment",pos:"n.",th:"ช่องเก็บของ, การแบ่งส่วน",ex:"",exTh:"",day:5},
{en:"give way to",pos:"phr.",th:"หลีกทางให้, ยอมจำนน",ex:"",exTh:"",day:5},
{en:"overwork",pos:"n./v.",th:"การทำงานหนักเกินไป; ทำงานหนักเกินไป",ex:"",exTh:"",day:5},
{en:"put down",pos:"phr.",th:"วางลง, เลิกงาน",ex:"",exTh:"",day:5},
{en:"reach the solution",pos:"phr.",th:"หาทางออกได้",ex:"",exTh:"",day:5},
{en:"recharge",pos:"v.",th:"ชาร์จใหม่, เพิ่มพลัง",ex:"",exTh:"",day:5},
{en:"smock",pos:"n.",th:"เสื้อคลุมหลวมๆ",ex:"",exTh:"",day:5},
{en:"accessibility",pos:"n.",th:"ความสามารถในการเข้าถึง",ex:"",exTh:"",day:5},
{en:"coordinator",pos:"n.",th:"ผู้ประสานงาน",ex:"",exTh:"",day:5},
{en:"customary",pos:"adj.",th:"ที่เป็นธรรมเนียมปฏิบัติ, เป็นปกติ",ex:"",exTh:"",day:5},
{en:"disrupt",pos:"v.",th:"ขัดจังหวะ, ขัดขวาง",ex:"",exTh:"",day:5},
{en:"elevate",pos:"v.",th:"ยกระดับ",ex:"",exTh:"",day:5},
{en:"formality",pos:"n.",th:"ความเป็นทางการ, พิธีการ",ex:"",exTh:"",day:5},
{en:"restraint",pos:"n.",th:"ข้อจำกัด, การยับยั้ง",ex:"",exTh:"",day:5},
{en:"sign out",pos:"phr.",th:"ลงชื่อออกจากระบบ",ex:"",exTh:"",day:5},
{en:"undeniable",pos:"adj.",th:"ที่ปฏิเสธไม่ได้",ex:"",exTh:"",day:5},
{en:"violation",pos:"n.",th:"การฝ่าฝืน, การละเมิด",ex:"",exTh:"",day:5},
{en:"aggravate",pos:"v.",th:"ก่อกวน, ทำให้แย่ลง",ex:"",exTh:"",day:5},
{en:"contingency",pos:"n.",th:"ความบังเอิญ, ความไม่แน่นอน",ex:"",exTh:"",day:5},
{en:"draw the line at",pos:"phr.",th:"ขีดเส้นกำหนด, ไม่ยอมเกินกว่านี้",ex:"",exTh:"",day:5},
{en:"draw up",pos:"phr.",th:"ร่าง (เอกสาร)",ex:"",exTh:"",day:5},
{en:"evacuate",pos:"v.",th:"อพยพ",ex:"",exTh:"",day:5},
{en:"in commemoration of",pos:"phr.",th:"เพื่อเป็นการระลึกถึง",ex:"",exTh:"",day:5},
{en:"on probation",pos:"phr.",th:"ที่โดนภาคทัณฑ์, ช่วงทดลองงาน",ex:"",exTh:"",day:5},
{en:"overestimate",pos:"v.",th:"ประเมินค่าสูงเกินไป",ex:"",exTh:"",day:5},
{en:"privilege",pos:"n.",th:"เอกสิทธิ์, สิทธิพิเศษ",ex:"",exTh:"",day:5},
{en:"restructure",pos:"v.",th:"ปรับโครงสร้างใหม่",ex:"",exTh:"",day:5},
{en:"segregate A from B",pos:"phr.",th:"แยก A ออกจาก B",ex:"",exTh:"",day:5},
{en:"trigger",pos:"v.",th:"กระตุ้น, เหนี่ยวไก",ex:"",exTh:"",day:5},
{en:"wary of",pos:"phr.",th:"ระวัง, ระแวง",ex:"",exTh:"",day:5},
/* ===== DAY 06 : เวลาว่าง / การเข้าสังคม ===== */
{en:"backpack",pos:"n.",th:"เป้สะพายหลัง",ex:"",exTh:"",day:6},
{en:"bike",pos:"n.",th:"จักรยาน",ex:"",exTh:"",day:6},
{en:"cabin",pos:"n.",th:"กระท่อม, ห้องโดยสาร",ex:"",exTh:"",day:6},
{en:"climb a mountain",pos:"phr.",th:"ปีนเขา",ex:"",exTh:"",day:6},
{en:"film festival",pos:"phr.",th:"เทศกาลภาพยนตร์",ex:"",exTh:"",day:6},
{en:"fishing",pos:"n.",th:"การตกปลา",ex:"",exTh:"",day:6},
{en:"gallery",pos:"n.",th:"ห้องแสดงศิลปะ, แกลเลอรี, หอศิลป์",ex:"",exTh:"",day:6},
{en:"invitation",pos:"n.",th:"การเชื้อเชิญ, คำเชิญ",ex:"",exTh:"",day:6},
{en:"lawn",pos:"n.",th:"สนามหญ้า",ex:"",exTh:"",day:6},
{en:"paint",pos:"n./v.",th:"สี; ทาสี, วาดรูป",ex:"",exTh:"",day:6},
{en:"painting",pos:"n.",th:"ภาพวาด",ex:"",exTh:"",day:6},
{en:"play cards",pos:"phr.",th:"เล่นไพ่",ex:"",exTh:"",day:6},
{en:"public library",pos:"phr.",th:"หอสมุดสาธารณะ",ex:"",exTh:"",day:6},
{en:"race",pos:"n./v.",th:"การแข่งขัน; แข่งขัน",ex:"",exTh:"",day:6},
{en:"resort",pos:"n.",th:"รีสอร์ต, ที่พักตากอากาศ",ex:"",exTh:"",day:6},
{en:"theater",pos:"n.",th:"โรงละคร, โรงภาพยนตร์",ex:"",exTh:"",day:6},
{en:"watch a film",pos:"phr.",th:"ดูภาพยนตร์",ex:"",exTh:"",day:6},
{en:"adventure",pos:"n.",th:"การผจญภัย",ex:"",exTh:"",day:6},
{en:"art museum",pos:"phr.",th:"พิพิธภัณฑ์ศิลปะ",ex:"",exTh:"",day:6},
{en:"begin",pos:"v.",th:"เริ่มต้น",ex:"",exTh:"",day:6},
{en:"bring",pos:"v.",th:"นำมา, พามา",ex:"",exTh:"",day:6},
{en:"care for",pos:"phr.",th:"ใส่ใจ, ห่วงใย, ดูแล",ex:"",exTh:"",day:6},
{en:"concert",pos:"n.",th:"คอนเสิร์ต, งานแสดงดนตรี",ex:"",exTh:"",day:6},
{en:"length",pos:"n.",th:"ความยาว",ex:"",exTh:"",day:6},
{en:"leisure",pos:"n.",th:"เวลาว่าง",ex:"",exTh:"",day:6},
{en:"librarian",pos:"n.",th:"บรรณารักษ์",ex:"",exTh:"",day:6},
{en:"menu",pos:"n.",th:"เมนู, รายการอาหาร",ex:"",exTh:"",day:6},
{en:"sightseeing",pos:"n.",th:"การเที่ยวชมสถานที่ท่องเที่ยว",ex:"",exTh:"",day:6},
{en:"amusement park",pos:"phr.",th:"สวนสนุก",ex:"",exTh:"",day:6},
{en:"ancient history",pos:"phr.",th:"ประวัติศาสตร์ที่เก่าแก่",ex:"",exTh:"",day:6},
{en:"artifact",pos:"n.",th:"สิ่งประดิษฐ์, โบราณวัตถุ",ex:"",exTh:"",day:6},
{en:"auditorium",pos:"n.",th:"หอประชุม",ex:"",exTh:"",day:6},
{en:"be booked up",pos:"phr.",th:"จองเต็ม",ex:"",exTh:"",day:6},
{en:"box office",pos:"phr.",th:"ช่องขายตั๋ว",ex:"",exTh:"",day:6},
{en:"cheerful",pos:"adj.",th:"ร่าเริง",ex:"",exTh:"",day:6},
{en:"choir",pos:"n.",th:"วงนักร้องประสานเสียง",ex:"",exTh:"",day:6},
{en:"entertain",pos:"v.",th:"ทำให้สนุกสนาน",ex:"",exTh:"",day:6},
{en:"flower arrangement",pos:"phr.",th:"การจัดดอกไม้",ex:"",exTh:"",day:6},
{en:"flower bed",pos:"phr.",th:"แปลงต้นไม้/ดอกไม้",ex:"",exTh:"",day:6},
{en:"go to a film",pos:"phr.",th:"ไปดูภาพยนตร์",ex:"",exTh:"",day:6},
{en:"grip",pos:"v.",th:"กำ, บีบ, จับแน่น",ex:"",exTh:"",day:6},
{en:"have a race",pos:"phr.",th:"เข้าแข่งขัน",ex:"",exTh:"",day:6},
{en:"jog along the street",pos:"phr.",th:"วิ่งเหยาะๆ ไปตามถนน",ex:"",exTh:"",day:6},
{en:"musical instrument",pos:"phr.",th:"เครื่องดนตรี",ex:"",exTh:"",day:6},
{en:"oar",pos:"n./v.",th:"ไม้พาย; พายเรือ",ex:"",exTh:"",day:6},
{en:"oil painting",pos:"phr.",th:"ภาพสีน้ำมัน",ex:"",exTh:"",day:6},
{en:"outdoor",pos:"adj.",th:"ที่อยู่นอกอาคาร",ex:"",exTh:"",day:6},
{en:"paddle",pos:"v.",th:"พายเรือ",ex:"",exTh:"",day:6},
{en:"premiere",pos:"n.",th:"รอบปฐมทัศน์",ex:"",exTh:"",day:6},
{en:"rake leaves",pos:"phr.",th:"ใช้คราดกวาดใบไม้",ex:"",exTh:"",day:6},
{en:"recreational activity",pos:"phr.",th:"กิจกรรมนันทนาการ",ex:"",exTh:"",day:6},
{en:"right",pos:"n./adj.",th:"สิทธิ; ถูกต้อง",ex:"",exTh:"",day:6},
{en:"running time",pos:"phr.",th:"ระยะเวลาที่ภาพยนตร์/ละครฉาย",ex:"",exTh:"",day:6},
{en:"sail a boat",pos:"phr.",th:"ล่องเรือใบ",ex:"",exTh:"",day:6},
{en:"slide down",pos:"phr.",th:"ไถลลง",ex:"",exTh:"",day:6},
{en:"splash",pos:"v.",th:"กระเด็น, สาดน้ำ",ex:"",exTh:"",day:6},
{en:"sport tournament",pos:"phr.",th:"การแข่งขันกีฬา",ex:"",exTh:"",day:6},
{en:"stadium",pos:"n.",th:"สนามกีฬา, อัฒจันทร์",ex:"",exTh:"",day:6},
{en:"stay up",pos:"phr.",th:"นอนดึก",ex:"",exTh:"",day:6},
{en:"stroll",pos:"v.",th:"เดินเล่น, เดินทอดน่อง",ex:"",exTh:"",day:6},
{en:"take a break",pos:"phr.",th:"พักชั่วคราว",ex:"",exTh:"",day:6},
{en:"take A for a walk",pos:"phr.",th:"พา...ไปเดินเล่น",ex:"",exTh:"",day:6},
{en:"take a photograph",pos:"phr.",th:"ถ่ายภาพ",ex:"",exTh:"",day:6},
{en:"take a walk",pos:"phr.",th:"เดินเล่น",ex:"",exTh:"",day:6},
{en:"take great pleasure",pos:"phr.",th:"มีความสุขมากๆ, สนุก",ex:"",exTh:"",day:6},
{en:"touch up a photograph",pos:"phr.",th:"แต่งรูปภาพ",ex:"",exTh:"",day:6},
{en:"vacation package",pos:"phr.",th:"แพ็กเกจท่องเที่ยว",ex:"",exTh:"",day:6},
{en:"wait for seats",pos:"phr.",th:"รอที่นั่งว่าง",ex:"",exTh:"",day:6},
{en:"wait in line",pos:"phr.",th:"เข้าแถวรอ",ex:"",exTh:"",day:6},
{en:"water the plants",pos:"phr.",th:"รดน้ำต้นไม้",ex:"",exTh:"",day:6},
{en:"amuse",pos:"v.",th:"ทำให้ตลก/สนุก",ex:"",exTh:"",day:6},
{en:"artistic",pos:"adj.",th:"เกี่ยวกับศิลปะ",ex:"",exTh:"",day:6},
{en:"donate",pos:"v.",th:"บริจาค",ex:"",exTh:"",day:6},
{en:"even though",pos:"phr.",th:"แม้ว่า",ex:"",exTh:"",day:6},
{en:"exhibit",pos:"v.",th:"จัดแสดงนิทรรศการ",ex:"",exTh:"",day:6},
{en:"free admission",pos:"phr.",th:"ไม่ต้องเสียค่าเข้าชม",ex:"",exTh:"",day:6},
{en:"make oneself at home",pos:"phr.",th:"ทำตัวตามสบาย",ex:"",exTh:"",day:6},
{en:"municipal",pos:"adj.",th:"เกี่ยวกับเทศบาล/ท้องถิ่น",ex:"",exTh:"",day:6},
{en:"owed",pos:"adj.",th:"ติดหนี้, ติดเงิน",ex:"",exTh:"",day:6},
{en:"several",pos:"adj.",th:"หลากหลาย, หลายอย่าง",ex:"",exTh:"",day:6},
{en:"spectator",pos:"n.",th:"ผู้เข้าชม",ex:"",exTh:"",day:6},
{en:"usher",pos:"n.",th:"พนักงานนำไปยังที่นั่ง (โรงภาพยนตร์)",ex:"",exTh:"",day:6},
{en:"win a contest",pos:"phr.",th:"ชนะการประกวด",ex:"",exTh:"",day:6},
{en:"admission to",pos:"phr.",th:"การเข้าไปยัง...",ex:"",exTh:"",day:6},
{en:"contestant",pos:"n.",th:"ผู้เข้าประกวด",ex:"",exTh:"",day:6},
{en:"delight",pos:"n.",th:"ความปลื้มปีติ",ex:"",exTh:"",day:6},
{en:"do one's hair",pos:"phr.",th:"ทำผม",ex:"",exTh:"",day:6},
{en:"enjoyable",pos:"adj.",th:"สนุกสนาน, น่าเพลิดเพลิน",ex:"",exTh:"",day:6},
{en:"group rate",pos:"phr.",th:"อัตราราคาแบบกลุ่ม",ex:"",exTh:"",day:6},
{en:"head for",pos:"phr.",th:"มุ่งหน้าไปยัง",ex:"",exTh:"",day:6},
{en:"out of order",pos:"phr.",th:"พัง, เสีย, ใช้การไม่ได้",ex:"",exTh:"",day:6},
{en:"periodical",pos:"n./adj.",th:"วารสารตามกำหนดเวลา; ที่เกิดเป็นระยะๆ",ex:"",exTh:"",day:6},
{en:"playing field",pos:"phr.",th:"สนามกีฬา",ex:"",exTh:"",day:6},
{en:"register for",pos:"phr.",th:"ลงทะเบียน",ex:"",exTh:"",day:6},
{en:"show up",pos:"phr.",th:"โผล่, ปรากฏตัว",ex:"",exTh:"",day:6},
{en:"take a tour",pos:"phr.",th:"เดินชม/เที่ยวดูสถานที่ต่างๆ",ex:"",exTh:"",day:6},
{en:"be in line",pos:"phr.",th:"เข้าแถวรอ",ex:"",exTh:"",day:6},
{en:"for a change",pos:"phr.",th:"เพื่อการเปลี่ยนบรรยากาศ",ex:"",exTh:"",day:6},
{en:"pass the time",pos:"phr.",th:"ฆ่าเวลา",ex:"",exTh:"",day:6},
{en:"pose",pos:"v./n.",th:"วางท่าทาง; ท่าทาง",ex:"",exTh:"",day:6},
{en:"stay tuned",pos:"phr.",th:"อย่าเปลี่ยนช่อง (วิทยุ/ทีวี)",ex:"",exTh:"",day:6},
{en:"vacate",pos:"v.",th:"ออกจาก, พ้นตำแหน่ง",ex:"",exTh:"",day:6},
{en:"appreciative",pos:"adj.",th:"ซึ่งรู้สึกขอบคุณ",ex:"",exTh:"",day:6},
{en:"casually",pos:"adv.",th:"ง่ายๆ, ไม่เป็นทางการ",ex:"",exTh:"",day:6},
{en:"enlightening",pos:"adj.",th:"ที่ทำให้กระจ่าง, ที่ให้ความรู้",ex:"",exTh:"",day:6},
{en:"enthusiastically",pos:"adv.",th:"อย่างกระตือรือร้น",ex:"",exTh:"",day:6},
{en:"excellence",pos:"n.",th:"ความยอดเยี่ยม",ex:"",exTh:"",day:6},
{en:"excursion",pos:"n.",th:"การไปเที่ยวใกล้ๆ ระยะสั้น",ex:"",exTh:"",day:6},
{en:"festivity",pos:"n.",th:"การเฉลิมฉลอง, งานรื่นเริง",ex:"",exTh:"",day:6},
{en:"flock",pos:"v./n.",th:"รวมตัว, จับกลุ่ม; ฝูงสัตว์",ex:"",exTh:"",day:6},
{en:"intriguingly",pos:"adv.",th:"อย่างน่าสนใจ",ex:"",exTh:"",day:6},
{en:"legroom",pos:"phr.",th:"พื้นที่ว่างสำหรับเหยียดขา",ex:"",exTh:"",day:6},
{en:"mural",pos:"n.",th:"จิตรกรรมฝาผนัง",ex:"",exTh:"",day:6},
{en:"portrait",pos:"n.",th:"ภาพวาดบุคคล",ex:"",exTh:"",day:6},
{en:"publication",pos:"n.",th:"การตีพิมพ์, สิ่งพิมพ์",ex:"",exTh:"",day:6},
{en:"sculpture",pos:"n.",th:"ประติมากรรม",ex:"",exTh:"",day:6},
{en:"transferable",pos:"adj.",th:"ที่สามารถโอน/ย้ายได้",ex:"",exTh:"",day:6},
{en:"unsanitary",pos:"adj.",th:"ไม่สะอาด, ไม่ถูกสุขอนามัย",ex:"",exTh:"",day:6},
{en:"be in the mood for",pos:"phr.",th:"มีอารมณ์ที่จะ...",ex:"",exTh:"",day:6},
{en:"botanical garden",pos:"phr.",th:"สวนพฤกษชาติ",ex:"",exTh:"",day:6},
{en:"censorship",pos:"n.",th:"การเซ็นเซอร์, การตรวจเนื้อหา",ex:"",exTh:"",day:6},
{en:"have yet to do",pos:"phr.",th:"ยังไม่ได้...",ex:"",exTh:"",day:6},
{en:"intermission",pos:"n.",th:"การหยุดพักสลับฉาก",ex:"",exTh:"",day:6},
{en:"memoirs",pos:"n.",th:"บันทึกความทรงจำ",ex:"",exTh:"",day:6},
{en:"must-see",pos:"adj.",th:"ที่ต้องดู, ที่ห้ามพลาด",ex:"",exTh:"",day:6},
{en:"rally",pos:"n.",th:"การชุมนุมสาธารณะ",ex:"",exTh:"",day:6},
{en:"ridiculous",pos:"adj.",th:"งี่เง่า, ไร้สาระ, น่าขำ",ex:"",exTh:"",day:6},
{en:"roam around",pos:"phr.",th:"เที่ยวไปเรื่อยๆ, เที่ยวเตร่",ex:"",exTh:"",day:6},
/* ===== DAY 07 : การตลาด (1) ===== */
{en:"after all",pos:"phr.",th:"อย่างไรก็ตาม, ท้ายที่สุด",ex:"",exTh:"",day:7},
{en:"answer the phone",pos:"phr.",th:"รับโทรศัพท์",ex:"",exTh:"",day:7},
{en:"as it is",pos:"phr.",th:"ตามที่เป็น",ex:"",exTh:"",day:7},
{en:"be based on",pos:"phr.",th:"ขึ้นอยู่กับ, อิงจาก",ex:"",exTh:"",day:7},
{en:"be familiar with",pos:"phr.",th:"คุ้นเคยกับ",ex:"",exTh:"",day:7},
{en:"concrete",pos:"adj.",th:"เป็นรูปธรรม, ชัดเจน, มีตัวตน",ex:"",exTh:"",day:7},
{en:"conflict with",pos:"phr.",th:"มีปัญหากับ, ขัดแย้งกับ",ex:"",exTh:"",day:7},
{en:"on display",pos:"phr.",th:"จัดแสดงไว้ให้เห็น",ex:"",exTh:"",day:7},
{en:"shadow",pos:"n.",th:"เงา, ร่มเงา",ex:"",exTh:"",day:7},
{en:"around the world",pos:"phr.",th:"ทั่วโลก, รอบโลก",ex:"",exTh:"",day:7},
{en:"array",pos:"n.",th:"การจัดเรียง, แถวลำดับ",ex:"",exTh:"",day:7},
{en:"attempt",pos:"v./n.",th:"พยายาม; ความพยายาม",ex:"",exTh:"",day:7},
{en:"audiovisual",pos:"adj.",th:"เกี่ยวกับเสียงและภาพ",ex:"",exTh:"",day:7},
{en:"avoid",pos:"v.",th:"หลีกเลี่ยง",ex:"",exTh:"",day:7},
{en:"based",pos:"adj.",th:"ซึ่งเป็นรากฐาน",ex:"",exTh:"",day:7},
{en:"cinema",pos:"n.",th:"โรงภาพยนตร์",ex:"",exTh:"",day:7},
{en:"competitive",pos:"adj.",th:"ที่มีการแข่งขันสูง",ex:"",exTh:"",day:7},
{en:"conclude",pos:"v.",th:"สรุป",ex:"",exTh:"",day:7},
{en:"energy drink",pos:"phr.",th:"เครื่องดื่มชูกำลัง",ex:"",exTh:"",day:7},
{en:"find out",pos:"phr.",th:"ค้นพบ, หาคำตอบ",ex:"",exTh:"",day:7},
{en:"informal",pos:"adj.",th:"ไม่เป็นทางการ, กันเอง",ex:"",exTh:"",day:7},
{en:"marketplace",pos:"n.",th:"สถานที่ซื้อขายสินค้า, ตลาด",ex:"",exTh:"",day:7},
{en:"pattern",pos:"n.",th:"รูปแบบ, ลวดลาย, ธรรมเนียมปฏิบัติ",ex:"",exTh:"",day:7},
{en:"public relations (PR) department",pos:"phr.",th:"แผนกประชาสัมพันธ์",ex:"",exTh:"",day:7},
{en:"sales",pos:"n.",th:"การขาย, ยอดขาย, ฝ่ายขาย",ex:"",exTh:"",day:7},
{en:"strict",pos:"adj.",th:"เข้มงวด",ex:"",exTh:"",day:7},
{en:"tool",pos:"n.",th:"เครื่องมือ",ex:"",exTh:"",day:7},
{en:"typical",pos:"adj.",th:"ที่เป็นแบบฉบับ, ทั่วไป",ex:"",exTh:"",day:7},
{en:"a piece of equipment",pos:"phr.",th:"เครื่องมือ/อุปกรณ์หนึ่งชิ้น",ex:"",exTh:"",day:7},
{en:"all the way",pos:"phr.",th:"ทั้งหมด, จนถึงที่สุด",ex:"",exTh:"",day:7},
{en:"appealing",pos:"adj.",th:"น่าดึงดูด, น่าสนใจ",ex:"",exTh:"",day:7},
{en:"at once",pos:"phr.",th:"ทันที",ex:"",exTh:"",day:7},
{en:"definite",pos:"adj.",th:"แน่นอน, ชัดเจน",ex:"",exTh:"",day:7},
{en:"distinguish",pos:"v.",th:"แยกแยะความแตกต่าง",ex:"",exTh:"",day:7},
{en:"extraordinary",pos:"adj.",th:"ที่เหนือธรรมดา, พิเศษมากๆ",ex:"",exTh:"",day:7},
{en:"good for",pos:"phr.",th:"ดีต่อ...",ex:"",exTh:"",day:7},
{en:"in bloom",pos:"phr.",th:"กำลังเบ่งบาน",ex:"",exTh:"",day:7},
{en:"in reference to",pos:"phr.",th:"อ้างอิงถึง...",ex:"",exTh:"",day:7},
{en:"market stall",pos:"phr.",th:"ร้านแผงลอย",ex:"",exTh:"",day:7},
{en:"mechanism",pos:"n.",th:"กลไก",ex:"",exTh:"",day:7},
{en:"metropolitan area",pos:"phr.",th:"เขตมหานคร, เขตเมือง",ex:"",exTh:"",day:7},
{en:"national holiday",pos:"phr.",th:"วันชาติ, วันหยุดราชการ",ex:"",exTh:"",day:7},
{en:"on schedule",pos:"phr.",th:"ตามตาราง, ตามกำหนด",ex:"",exTh:"",day:7},
{en:"over the Internet",pos:"phr.",th:"บนอินเทอร์เน็ต",ex:"",exTh:"",day:7},
{en:"preview",pos:"n.",th:"การชมก่อน, การแสดงตัวอย่าง",ex:"",exTh:"",day:7},
{en:"public display",pos:"phr.",th:"การเปิดเผย/แสดงต่อหน้าสาธารณะ",ex:"",exTh:"",day:7},
{en:"run a campaign",pos:"phr.",th:"ทำกิจกรรม, รณรงค์",ex:"",exTh:"",day:7},
{en:"serve a customer",pos:"phr.",th:"บริการลูกค้า",ex:"",exTh:"",day:7},
{en:"spouse",pos:"n.",th:"สามีหรือภรรยา, คู่สมรส",ex:"",exTh:"",day:7},
{en:"upside down",pos:"phr.",th:"กลับหัว",ex:"",exTh:"",day:7},
{en:"vending machine",pos:"phr.",th:"เครื่องจำหน่ายสินค้าแบบหยอดเหรียญ",ex:"",exTh:"",day:7},
{en:"visible",pos:"adj.",th:"ที่สามารถมองเห็นได้",ex:"",exTh:"",day:7},
{en:"as opposed to",pos:"phr.",th:"แทนที่, ตรงกันข้ามกับ",ex:"",exTh:"",day:7},
{en:"boldly",pos:"adv.",th:"อย่างกล้าหาญ",ex:"",exTh:"",day:7},
{en:"call on",pos:"phr.",th:"เรียกร้อง, แวะเยี่ยม",ex:"",exTh:"",day:7},
{en:"excluding",pos:"prep.",th:"ยกเว้น, ไม่รวม",ex:"",exTh:"",day:7},
{en:"expectancy",pos:"n.",th:"ความคาดหมาย",ex:"",exTh:"",day:7},
{en:"forgetfully",pos:"adv.",th:"อย่างหลงๆ ลืมๆ",ex:"",exTh:"",day:7},
{en:"noteworthy",pos:"adj.",th:"โดดเด่น, น่าจดจำ",ex:"",exTh:"",day:7},
{en:"perception",pos:"n.",th:"ความเข้าใจ, การรับรู้",ex:"",exTh:"",day:7},
{en:"potentially",pos:"adv.",th:"ที่มีโอกาสเป็นไปได้",ex:"",exTh:"",day:7},
{en:"randomly",pos:"adv.",th:"สุ่ม, ไม่เรียงลำดับ",ex:"",exTh:"",day:7},
{en:"suitable",pos:"adj.",th:"เหมาะสม",ex:"",exTh:"",day:7},
{en:"a complete line of",pos:"phr.",th:"ผลิตภัณฑ์...ทั้งหมด (ครบไลน์)",ex:"",exTh:"",day:7},
{en:"accept the offer",pos:"phr.",th:"ยอมรับข้อเสนอ",ex:"",exTh:"",day:7},
{en:"astonishingly",pos:"adv.",th:"อย่างน่าประหลาดใจ",ex:"",exTh:"",day:7},
{en:"be noted for",pos:"phr.",th:"มีชื่อเสียงในด้าน",ex:"",exTh:"",day:7},
{en:"claim",pos:"n.",th:"การอ้างสิทธิ์, การเรียกร้อง",ex:"",exTh:"",day:7},
{en:"classified ad",pos:"phr.",th:"โฆษณาย่อย",ex:"",exTh:"",day:7},
{en:"compilation",pos:"n.",th:"การรวบรวม",ex:"",exTh:"",day:7},
{en:"comprehensible",pos:"adj.",th:"ที่สามารถเข้าใจได้",ex:"",exTh:"",day:7},
{en:"criticize",pos:"v.",th:"วิจารณ์",ex:"",exTh:"",day:7},
{en:"dumping",pos:"n.",th:"การทุ่มตลาด",ex:"",exTh:"",day:7},
{en:"first priority",pos:"phr.",th:"สิ่งสำคัญอันดับแรก",ex:"",exTh:"",day:7},
{en:"fixed price",pos:"phr.",th:"ราคาตายตัว",ex:"",exTh:"",day:7},
{en:"have control over",pos:"phr.",th:"มีอำนาจควบคุมเหนือ...",ex:"",exTh:"",day:7},
{en:"have little chance of",pos:"phr.",th:"มีโอกาสน้อยที่จะ...",ex:"",exTh:"",day:7},
{en:"in favor of",pos:"phr.",th:"เห็นด้วย, สนับสนุน",ex:"",exTh:"",day:7},
{en:"keep A informed of B",pos:"phr.",th:"แจ้งเรื่อง B ให้ A ทราบ",ex:"",exTh:"",day:7},
{en:"make an assessment",pos:"phr.",th:"ประเมิน",ex:"",exTh:"",day:7},
{en:"mediate",pos:"v.",th:"ไกล่เกลี่ย, เป็นสื่อกลาง",ex:"",exTh:"",day:7},
{en:"minimize the risk of",pos:"phr.",th:"ลดความเสี่ยงของ...",ex:"",exTh:"",day:7},
{en:"modestly",pos:"adv.",th:"พอประมาณ, อย่างถ่อมตัว",ex:"",exTh:"",day:7},
{en:"persistent",pos:"adj.",th:"ต่อเนื่องยาวนาน, ยืนหยัด",ex:"",exTh:"",day:7},
{en:"publicity",pos:"n.",th:"การเผยแพร่ต่อสาธารณะ, การโฆษณา",ex:"",exTh:"",day:7},
{en:"release date",pos:"phr.",th:"วันที่เผยแพร่/ปล่อยสู่ตลาด",ex:"",exTh:"",day:7},
{en:"stay competitive",pos:"phr.",th:"รักษาความสามารถในการแข่งขัน",ex:"",exTh:"",day:7},
{en:"striking difference",pos:"phr.",th:"ความแตกต่างที่เห็นได้ชัด",ex:"",exTh:"",day:7},
{en:"take a long time",pos:"phr.",th:"ใช้เวลานาน",ex:"",exTh:"",day:7},
{en:"take action",pos:"phr.",th:"ลงมือทำ, เริ่มมีบทบาท",ex:"",exTh:"",day:7},
{en:"trademark",pos:"n.",th:"เครื่องหมายการค้า",ex:"",exTh:"",day:7},
{en:"turn to",pos:"phr.",th:"หันไปหา..., กลับไปสู่...",ex:"",exTh:"",day:7},
{en:"unacceptable",pos:"adj.",th:"ที่ยอมรับไม่ได้",ex:"",exTh:"",day:7},
{en:"verify",pos:"v.",th:"พิสูจน์/ยืนยันว่าเป็นความจริง",ex:"",exTh:"",day:7},
{en:"with the exception of",pos:"phr.",th:"ยกเว้น...",ex:"",exTh:"",day:7},
{en:"without notice",pos:"phr.",th:"โดยไม่แจ้งให้ทราบ",ex:"",exTh:"",day:7},
{en:"all-out",pos:"phr.",th:"ทั้งหมด, อย่างเต็มที่",ex:"",exTh:"",day:7},
{en:"all walks of life",pos:"phr.",th:"ทุกชนชั้นทางสังคม",ex:"",exTh:"",day:7},
{en:"at a stretch",pos:"phr.",th:"ต่อเนื่อง, รวดเดียว",ex:"",exTh:"",day:7},
{en:"back up",pos:"phr.",th:"สำรอง, สนับสนุน, หนุนหลัง",ex:"",exTh:"",day:7},
{en:"focus group",pos:"phr.",th:"กลุ่มเป้าหมาย (สำรวจความเห็น)",ex:"",exTh:"",day:7},
{en:"misleading",pos:"adj.",th:"ที่นำไปในทางผิด, หลอกลวง",ex:"",exTh:"",day:7},
{en:"capture",pos:"v.",th:"จับกุม, เข้าครอบครอง, ฉวย",ex:"",exTh:"",day:7},
{en:"consolidate",pos:"v.",th:"ทำให้เป็นปึกแผ่น, รวมเข้าด้วยกัน",ex:"",exTh:"",day:7},
{en:"contend",pos:"v.",th:"โต้เถียง, ต่อสู้",ex:"",exTh:"",day:7},
{en:"gauge",pos:"v.",th:"วัด, ประเมิน",ex:"",exTh:"",day:7},
{en:"momentum",pos:"n.",th:"แรงผลักดัน, แรงกระตุ้น",ex:"",exTh:"",day:7},
{en:"recognizable",pos:"adj.",th:"ที่พอจดจำได้, เป็นที่รู้จัก",ex:"",exTh:"",day:7},
{en:"segment",pos:"n.",th:"กลุ่ม, ท่อน, ตอน, ส่วน",ex:"",exTh:"",day:7},
{en:"telling",pos:"adj.",th:"มีผล, แสดงให้เห็นได้ดี",ex:"",exTh:"",day:7},
{en:"confiscation",pos:"n.",th:"การยึด, การริบ",ex:"",exTh:"",day:7},
{en:"constitute",pos:"v.",th:"ก่อตั้ง, ประกอบขึ้นเป็น",ex:"",exTh:"",day:7},
{en:"drive up",pos:"phr.",th:"ทำให้เพิ่มขึ้นอย่างรวดเร็ว",ex:"",exTh:"",day:7},
{en:"feasibility study",pos:"phr.",th:"การศึกษาความเป็นไปได้",ex:"",exTh:"",day:7},
{en:"intervention",pos:"n.",th:"การแทรกแซง",ex:"",exTh:"",day:7},
{en:"irretrievable",pos:"adj.",th:"ที่ไม่สามารถกู้คืนได้",ex:"",exTh:"",day:7},
{en:"jeopardize",pos:"v.",th:"ทำให้เสี่ยง, ทำให้อยู่ในอันตราย",ex:"",exTh:"",day:7},
{en:"legible",pos:"adj.",th:"ชัดเจน, อ่านออกได้",ex:"",exTh:"",day:7},
{en:"lose ground",pos:"phr.",th:"สูญเสียความนิยม/การสนับสนุน",ex:"",exTh:"",day:7},
{en:"public profile",pos:"phr.",th:"สถานะทางสังคม, ภาพลักษณ์ต่อสาธารณะ",ex:"",exTh:"",day:7},
{en:"reputable",pos:"adj.",th:"มีชื่อเสียง, น่าเชื่อถือ",ex:"",exTh:"",day:7},
{en:"set forth",pos:"phr.",th:"ออกเดินทาง, เริ่มต้น",ex:"",exTh:"",day:7},
{en:"set out",pos:"phr.",th:"ออกเดินทาง, เริ่มต้น, ลงมือ",ex:"",exTh:"",day:7},
{en:"setback",pos:"n.",th:"การเสื่อมถอย, ปัญหาที่ทำให้ล่าช้า",ex:"",exTh:"",day:7},
{en:"take a stand against",pos:"phr.",th:"ต่อต้าน, คัดค้าน (อย่างเปิดเผย)",ex:"",exTh:"",day:7},
{en:"underlying",pos:"adj.",th:"ที่แฝงอยู่, ที่เป็นพื้นฐาน",ex:"",exTh:"",day:7},
{en:"vanish",pos:"v.",th:"หายไป",ex:"",exTh:"",day:7},
{en:"wind up",pos:"phr.",th:"ยุติ, เลิกกิจการ",ex:"",exTh:"",day:7},
/* ===== DAY 08 : การตลาด (2) ===== */
{en:"celebration",pos:"n.",th:"การเฉลิมฉลอง",ex:"",exTh:"",day:8},
{en:"curious",pos:"adj.",th:"อยากรู้อยากเห็น",ex:"",exTh:"",day:8},
{en:"drop by",pos:"phr.",th:"แวะเยี่ยม",ex:"",exTh:"",day:8},
{en:"first step",pos:"phr.",th:"ขั้นตอนแรก",ex:"",exTh:"",day:8},
{en:"for now",pos:"phr.",th:"ณ ตอนนี้",ex:"",exTh:"",day:8},
{en:"gather",pos:"v.",th:"รวบรวม, รวมตัว",ex:"",exTh:"",day:8},
{en:"get together",pos:"phr.",th:"รวมตัว, พบปะ",ex:"",exTh:"",day:8},
{en:"hole",pos:"n.",th:"หลุม, รู",ex:"",exTh:"",day:8},
{en:"in total",pos:"phr.",th:"โดยรวม, ทั้งหมด",ex:"",exTh:"",day:8},
{en:"in use",pos:"phr.",th:"กำลังใช้งาน",ex:"",exTh:"",day:8},
{en:"practical",pos:"adj.",th:"เป็นประโยชน์, สมเหตุสมผล",ex:"",exTh:"",day:8},
{en:"shovel",pos:"n.",th:"พลั่ว",ex:"",exTh:"",day:8},
{en:"show",pos:"v./n.",th:"แสดง; การแสดง",ex:"",exTh:"",day:8},
{en:"space",pos:"n./v.",th:"ที่ว่าง, อวกาศ; เว้นระยะ",ex:"",exTh:"",day:8},
{en:"advertise",pos:"v.",th:"โฆษณา",ex:"",exTh:"",day:8},
{en:"belief",pos:"n.",th:"ความเชื่อ",ex:"",exTh:"",day:8},
{en:"belong to",pos:"phr.",th:"เป็นของ...",ex:"",exTh:"",day:8},
{en:"be open for business",pos:"phr.",th:"พร้อมทำธุรกิจ, เปิดทำการ",ex:"",exTh:"",day:8},
{en:"best-selling author",pos:"phr.",th:"นักเขียนที่มียอดขายดีที่สุด",ex:"",exTh:"",day:8},
{en:"consumer",pos:"n.",th:"ผู้บริโภค",ex:"",exTh:"",day:8},
{en:"entry fee",pos:"phr.",th:"ค่าเข้า",ex:"",exTh:"",day:8},
{en:"experiment",pos:"n.",th:"การทดลอง",ex:"",exTh:"",day:8},
{en:"findings",pos:"pl.",th:"ข้อมูล/ผลที่ได้จากการสำรวจ",ex:"",exTh:"",day:8},
{en:"full",pos:"adj.",th:"เต็ม",ex:"",exTh:"",day:8},
{en:"obviously",pos:"adv.",th:"อย่างเห็นได้ชัด",ex:"",exTh:"",day:8},
{en:"photographer",pos:"n.",th:"ช่างภาพ",ex:"",exTh:"",day:8},
{en:"primarily",pos:"adv.",th:"โดยส่วนมาก, เป็นหลัก",ex:"",exTh:"",day:8},
{en:"sales target",pos:"phr.",th:"เป้ายอดขาย",ex:"",exTh:"",day:8},
{en:"advertising campaign",pos:"phr.",th:"แคมเปญโฆษณา",ex:"",exTh:"",day:8},
{en:"be anxious to do",pos:"phr.",th:"กระวนกระวายใจที่จะ...",ex:"",exTh:"",day:8},
{en:"bring on",pos:"phr.",th:"ก่อให้เกิด, สร้าง (ปัญหา)",ex:"",exTh:"",day:8},
{en:"chase",pos:"v.",th:"ไล่ล่า, ไล่ตาม",ex:"",exTh:"",day:8},
{en:"come along",pos:"phr.",th:"เกิดขึ้น, พัฒนา, ก้าวหน้า",ex:"",exTh:"",day:8},
{en:"come loose",pos:"phr.",th:"หลวม, หลุด",ex:"",exTh:"",day:8},
{en:"conditional",pos:"adj.",th:"ที่มีเงื่อนไข",ex:"",exTh:"",day:8},
{en:"customer survey",pos:"phr.",th:"การสำรวจความคิดเห็นลูกค้า",ex:"",exTh:"",day:8},
{en:"date back to",pos:"phr.",th:"ย้อนกลับไปที่ (สมัย)",ex:"",exTh:"",day:8},
{en:"depict",pos:"v.",th:"พรรณนา, บรรยายภาพ",ex:"",exTh:"",day:8},
{en:"destruction",pos:"n.",th:"การทำลายล้าง",ex:"",exTh:"",day:8},
{en:"enter into",pos:"phr.",th:"เริ่ม, มีส่วนร่วม",ex:"",exTh:"",day:8},
{en:"get back to",pos:"phr.",th:"ตอบกลับ, กลับไปที่",ex:"",exTh:"",day:8},
{en:"gradual",pos:"adj.",th:"ค่อยๆ, ทีละเล็กทีละน้อย",ex:"",exTh:"",day:8},
{en:"inactive",pos:"adj.",th:"ที่ไม่ได้ใช้งาน, เฉื่อยชา",ex:"",exTh:"",day:8},
{en:"in the meantime",pos:"phr.",th:"ในขณะเดียวกัน, ในระหว่างนี้",ex:"",exTh:"",day:8},
{en:"invalid",pos:"adj.",th:"ที่ใช้ไม่ได้, เป็นโมฆะ",ex:"",exTh:"",day:8},
{en:"look over",pos:"phr.",th:"ตรวจสอบ, ตรวจดู",ex:"",exTh:"",day:8},
{en:"make up one's mind",pos:"idm.",th:"ตัดสินใจ",ex:"",exTh:"",day:8},
{en:"meaningful",pos:"adj.",th:"มีความหมาย, มีความสำคัญ",ex:"",exTh:"",day:8},
{en:"put a rush",pos:"phr.",th:"เร่ง, เร่งรัด",ex:"",exTh:"",day:8},
{en:"put a strain on",pos:"phr.",th:"กดดัน, ทำให้เครียด",ex:"",exTh:"",day:8},
{en:"put up with",pos:"phr.",th:"อดทนกับ...",ex:"",exTh:"",day:8},
{en:"reach for",pos:"phr.",th:"เอื้อมถึง..., คว้า",ex:"",exTh:"",day:8},
{en:"stay ahead of",pos:"phr.",th:"นำหน้า...",ex:"",exTh:"",day:8},
{en:"A as well as B",pos:"phr.",th:"A และ B, เช่นเดียวกับ",ex:"",exTh:"",day:8},
{en:"ample",pos:"adj.",th:"เพียงพอ, เกินพอ",ex:"",exTh:"",day:8},
{en:"a range of",pos:"phr.",th:"ช่วง, หลากหลายของ...",ex:"",exTh:"",day:8},
{en:"attend to a client",pos:"phr.",th:"ดูแล/ใส่ใจลูกค้า",ex:"",exTh:"",day:8},
{en:"confront",pos:"v.",th:"เผชิญหน้า",ex:"",exTh:"",day:8},
{en:"context",pos:"n.",th:"บริบท, สภาพแวดล้อม",ex:"",exTh:"",day:8},
{en:"despair",pos:"n.",th:"ความสิ้นหวัง",ex:"",exTh:"",day:8},
{en:"disconnected",pos:"adj.",th:"ที่ไม่ได้เชื่อมต่อ, ไม่เชื่อมโยง",ex:"",exTh:"",day:8},
{en:"dissatisfied",pos:"adj.",th:"ที่ไม่พอใจ",ex:"",exTh:"",day:8},
{en:"driven",pos:"adj.",th:"มุ่งมั่น, แน่วแน่",ex:"",exTh:"",day:8},
{en:"dynamic",pos:"adj.",th:"มีชีวิตชีวา, คล่องแคล่ว",ex:"",exTh:"",day:8},
{en:"eagerly await",pos:"phr.",th:"รออย่างกระตือรือร้น",ex:"",exTh:"",day:8},
{en:"enormous",pos:"adj.",th:"ใหญ่โต, มหึมา",ex:"",exTh:"",day:8},
{en:"fall behind",pos:"phr.",th:"ตามไม่ทัน, ล้าหลัง",ex:"",exTh:"",day:8},
{en:"feasible",pos:"adj.",th:"ที่เป็นไปได้",ex:"",exTh:"",day:8},
{en:"forwarding address",pos:"phr.",th:"ที่อยู่สำหรับส่งต่อ",ex:"",exTh:"",day:8},
{en:"get over",pos:"phr.",th:"ทำใจได้, ผ่านพ้นไป",ex:"",exTh:"",day:8},
{en:"impress",pos:"v.",th:"ทำให้ประทับใจ",ex:"",exTh:"",day:8},
{en:"inadequate",pos:"adj.",th:"ไม่เพียงพอ, ไม่ดีพอ",ex:"",exTh:"",day:8},
{en:"in a timely fashion",pos:"phr.",th:"ในเวลาที่เหมาะสม, ทันเวลา",ex:"",exTh:"",day:8},
{en:"irreplaceable",pos:"adj.",th:"ที่ไม่สามารถแทนที่ได้",ex:"",exTh:"",day:8},
{en:"limitation",pos:"n.",th:"ข้อจำกัด",ex:"",exTh:"",day:8},
{en:"massive",pos:"adj.",th:"ใหญ่โต, หนักมาก",ex:"",exTh:"",day:8},
{en:"point out",pos:"phr.",th:"ชี้ให้เห็น",ex:"",exTh:"",day:8},
{en:"rave review",pos:"phr.",th:"คำวิจารณ์ชื่นชมอย่างยิ่ง",ex:"",exTh:"",day:8},
{en:"repeatedly",pos:"adv.",th:"ซ้ำๆ, ซ้ำซาก",ex:"",exTh:"",day:8},
{en:"strategically",pos:"adv.",th:"ในเชิงกลยุทธ์",ex:"",exTh:"",day:8},
{en:"unveil",pos:"v.",th:"เปิดเผย, ประกาศ (ต่อสาธารณชน)",ex:"",exTh:"",day:8},
{en:"a great deal",pos:"phr.",th:"จำนวนมาก",ex:"",exTh:"",day:8},
{en:"be sensitive to",pos:"phr.",th:"อ่อนไหวต่อ...",ex:"",exTh:"",day:8},
{en:"bother to do",pos:"phr.",th:"อุตส่าห์ทำ... (เรื่องที่ไม่จำเป็น)",ex:"",exTh:"",day:8},
{en:"call off",pos:"phr.",th:"ยกเลิก",ex:"",exTh:"",day:8},
{en:"carry out market studies",pos:"phr.",th:"ศึกษาตลาด",ex:"",exTh:"",day:8},
{en:"come across",pos:"phr.",th:"พบ/เจอโดยบังเอิญ",ex:"",exTh:"",day:8},
{en:"contrive to do",pos:"phr.",th:"วางแผน/ออกอุบายที่จะ...",ex:"",exTh:"",day:8},
{en:"deliberate",pos:"adj.",th:"รอบคอบ, ที่เจตนา",ex:"",exTh:"",day:8},
{en:"discounted rate",pos:"phr.",th:"อัตราคิดลด",ex:"",exTh:"",day:8},
{en:"have a tendency to do",pos:"phr.",th:"มีแนวโน้มที่จะ...",ex:"",exTh:"",day:8},
{en:"have an opportunity to do",pos:"phr.",th:"มีโอกาสที่จะ...",ex:"",exTh:"",day:8},
{en:"have something to do with",pos:"phr.",th:"เกี่ยวข้องกับ",ex:"",exTh:"",day:8},
{en:"in turn",pos:"phr.",th:"ตามลำดับ, ในทางกลับกัน",ex:"",exTh:"",day:8},
{en:"make no exception",pos:"phr.",th:"ไม่มีข้อยกเว้น",ex:"",exTh:"",day:8},
{en:"televise",pos:"v.",th:"ถ่ายทอดทางโทรทัศน์",ex:"",exTh:"",day:8},
{en:"discipline",pos:"n.",th:"ระเบียบวินัย",ex:"",exTh:"",day:8},
{en:"jingle",pos:"n.",th:"เพลง/ดนตรีประกอบโฆษณา",ex:"",exTh:"",day:8},
{en:"mobility",pos:"n.",th:"ความสามารถในการเคลื่อนที่",ex:"",exTh:"",day:8},
{en:"abruptly",pos:"adv.",th:"ทันที, ฉับพลัน",ex:"",exTh:"",day:8},
{en:"absorbing",pos:"adj.",th:"ที่ดึงดูดความสนใจ",ex:"",exTh:"",day:8},
{en:"admiringly",pos:"adv.",th:"อย่างชื่นชม",ex:"",exTh:"",day:8},
{en:"at large",pos:"phr.",th:"ยังลอยนวล; โดยรวม, ทั่วไป",ex:"",exTh:"",day:8},
{en:"boast about",pos:"phr.",th:"โม้/โอ้อวดเรื่อง...",ex:"",exTh:"",day:8},
{en:"coincide with",pos:"phr.",th:"เกิดขึ้นพร้อมกับ...",ex:"",exTh:"",day:8},
{en:"correspondent",pos:"n.",th:"ผู้สื่อข่าว, ผู้ติดต่อทางจดหมาย",ex:"",exTh:"",day:8},
{en:"counterpart",pos:"n.",th:"ผู้ที่อยู่ในตำแหน่งเดียวกัน (คนละที่)",ex:"",exTh:"",day:8},
{en:"defeat",pos:"v./n.",th:"เอาชนะ; ความพ่ายแพ้",ex:"",exTh:"",day:8},
{en:"dominant",pos:"adj.",th:"ที่มีอำนาจเหนือกว่า",ex:"",exTh:"",day:8},
{en:"fabulous",pos:"adj.",th:"เลิศเลอ, ยอดเยี่ยม",ex:"",exTh:"",day:8},
{en:"fortify",pos:"v.",th:"เสริมความแข็งแกร่ง, ให้กำลังใจ",ex:"",exTh:"",day:8},
{en:"fundamental",pos:"adj.",th:"ที่เป็นพื้นฐาน",ex:"",exTh:"",day:8},
{en:"mingle",pos:"v.",th:"ผสม, พบปะผู้คน",ex:"",exTh:"",day:8},
{en:"nuisance",pos:"n.",th:"สิ่งก่อกวน, ความรำคาญใจ",ex:"",exTh:"",day:8},
{en:"preciously",pos:"adv.",th:"อย่างยิ่งยวด, สุดโต่ง",ex:"",exTh:"",day:8},
{en:"stark",pos:"adj.",th:"ยากลำบาก, สิ้นเชิง",ex:"",exTh:"",day:8},
{en:"steadiness",pos:"n.",th:"ความมั่นคง, ความหนักแน่น",ex:"",exTh:"",day:8},
{en:"alluring",pos:"adj.",th:"น่าดึงดูดใจ",ex:"",exTh:"",day:8},
{en:"assimilate",pos:"v.",th:"ปรับ, ทำความเข้าใจ, กลมกลืน",ex:"",exTh:"",day:8},
{en:"at all costs",pos:"phr.",th:"ไม่ว่าอย่างไรก็ตาม",ex:"",exTh:"",day:8},
{en:"await",pos:"v.",th:"รอ, รอคอย",ex:"",exTh:"",day:8},
{en:"captivate",pos:"v.",th:"ทำให้หลงใหล",ex:"",exTh:"",day:8},
{en:"culminate in",pos:"phr.",th:"สิ้นสุดที่, จบที่, ลงเอยที่",ex:"",exTh:"",day:8},
{en:"dissipate",pos:"v.",th:"ค่อยๆ น้อยลง; ใช้อย่างเปล่าประโยชน์",ex:"",exTh:"",day:8},
{en:"driving force",pos:"phr.",th:"แรงขับเคลื่อน",ex:"",exTh:"",day:8},
{en:"elicit",pos:"v.",th:"ล้วง/ดึงข้อมูลออกมา",ex:"",exTh:"",day:8},
{en:"overwhelming",pos:"adj.",th:"ท่วมท้น, ล้นหลาม",ex:"",exTh:"",day:8},
{en:"voiced",pos:"adj.",th:"ที่ใช้เส้นเสียงในการออกเสียง",ex:"",exTh:"",day:8},
];
if (typeof module !== 'undefined') { module.exports = BOOK_WORDS; }

